export const NER_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🌐' },
  { code: 'as', name: 'অসমীয়া (Assamese)', flag: '🌾' },
  { code: 'bn', name: 'বাংলা (Bengali)', flag: '⛵' },
  { code: 'mni', name: 'মৈতৈলোন্ (Manipuri)', flag: '🌸' },
  { code: 'kha', name: 'Khasi (Meghalaya)', flag: '⛰️' },
  { code: 'hi', name: 'हिन्दी (Hindi)', flag: '🇮🇳' }
];

export const NER_TRANSLATIONS = {
  en: {
    platformTitle: 'MemoMate — SIH NER Cognitive Platform',
    dementiaSubtitle: 'AI-Based Cognitive Gaming & Memory Assistance for Elderly Dementia Patients in North Eastern Region',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    goodNight: 'Good Night',
    activeMember: 'NER COGNITIVE MEMBER',
    dailyGoal: 'DAILY COGNITIVE GOAL',
    teaGardenTheme: 'Assam Tea Garden 🍃',
    loktakTheme: 'Loktak Floating Meadow 🪷',
    orientationHeader: 'Dementia Daily Memory Anchor 📍',
    orientationSub: 'North Eastern Region Location & Memory Assistance',
    todaysDate: "Today's Date & Time",
    currentSeason: 'Current Season in NER',
    medicationCheck: 'Morning Medication',
    medicationTaken: 'Taken ✓',
    medicationPending: 'Pending Reminder 🔔',
    memoryAnchorPrompt: 'Personal Memory Anchor',
    memoryAnchorText: 'You are at home in Guwahati, Assam. Today is a peaceful day surrounded by family.',
    startExercise: 'START 3D EXERCISE',
    navDashboard: 'Dashboard',
    navLeaderboard: 'Leaderboard',
    navExercises: 'Cognitive Exercises',
    navTelemetry: 'AI Health Telemetry',
    navPath: 'Cognitive Path',
    navMetrics: 'Metrics & Trends',
    navGarden: '3D Memory Garden',
    navCaregiver: 'Caregiver Portal',
    streak: 'Streak',
    level: 'Level',
    rank: 'Rank',
    audioOn: 'AUDIO ON',
    audioOff: 'AUDIO OFF',
    patientView: 'Patient View',
    caregiverView: 'Caregiver View',
    logout: 'Logout',
    readAnchorAloud: 'READ ANCHOR ALOUD',
    water3dGarden: 'WATER 3D GARDEN 💦',
    vrMode: 'TOGGLE VR MODE 👓'
  },
  as: {
    platformTitle: 'মেমোমেট — উত্তৰ-পূৰ্বাঞ্চল জ্ঞানভিত্তিক প্লেটফৰ্ম',
    dementiaSubtitle: 'উত্তৰ-পূৰ্বাঞ্চলৰ জেষ্ঠ্য ডিমেনচিয়া ৰোগীৰ বাবে কৃত্ৰিম বুদ্ধিমত্তাভিত্তিক স্মৰণ সহায়ক',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপৰাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    goodNight: 'শুভ ৰাত্ৰি',
    activeMember: 'সক্ৰিয় সদস্য',
    dailyGoal: 'দৈনিক লক্ষ্য',
    teaGardenTheme: 'অসমৰ চাহ বাগিচা 🍃',
    loktakTheme: 'লোকটাক উপত্যকা 🪷',
    orientationHeader: 'দৈনিক স্মৃতি সহায়ক 📍',
    orientationSub: 'উত্তৰ-পূৰ্বাঞ্চল স্মৃতি আৰু অৱস্থান নিৰ্দেশনা',
    todaysDate: 'আজিৰ তাৰিখ আৰু সময়',
    currentSeason: 'বৰ্তমান ঋতু',
    medicationCheck: 'ৰাতিপুৱাৰ ঔষধ',
    medicationTaken: 'গ্ৰহণ কৰা হ’ল ✓',
    medicationPending: 'মনত পেলোৱা হ’ব 🔔',
    memoryAnchorPrompt: 'ব্যক্তিগত স্মৃতি সহায়ক',
    memoryAnchorText: 'আপুনি গুৱাহাটীৰ নিজ গৃহত আছে। পৰিয়ালৰ সৈতে আজি এক সুন্দৰ দিন।',
    startExercise: 'অনুশীলন আৰম্ভ কৰক',
    navDashboard: 'ড্যাশবৰ্ড',
    navLeaderboard: 'লিডাৰবৰ্ড',
    navExercises: 'জ্ঞানভিত্তিক অনুশীলন',
    navTelemetry: 'এআই স্বাস্থ্য নিৰীক্ষণ',
    navPath: 'জ্ঞানভিত্তিক পথ',
    navMetrics: 'মেট্ৰিক আৰু ট্ৰেন্ড',
    navGarden: '৩ডি স্মৃতি উদ্যান',
    navCaregiver: 'যত্নলোৱা পৰ্টেল',
    streak: 'ষ্ট্ৰীক',
    level: 'স্তৰ',
    rank: 'ৰংক',
    audioOn: 'শব্দ অন',
    audioOff: 'শব্দ অফ',
    patientView: 'ৰোগীৰ দৰ্শন',
    caregiverView: 'যত্নলোৱাৰ দৰ্শন',
    logout: 'লগআউট',
    readAnchorAloud: 'শব্দ কৰি পঢ়ক',
    water3dGarden: '৩ডি উদ্যানত পানী দিয়ক 💦',
    vrMode: 'ভিআৰ মোড 👓'
  },
  bn: {
    platformTitle: 'মেমোমেট — উত্তর-পূর্বাঞ্চল জ্ঞানভিত্তিক প্ল্যাটফর্ম',
    dementiaSubtitle: 'উত্তর-পূর্ব ভারতের প্রবীণ ডিমেনশিয়া রোগীদের জন্য কৃত্রিম বুদ্ধিমত্তা ভিত্তিক স্মৃতি সহায়ক',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপরাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    goodNight: 'শুভ রাত্রি',
    activeMember: 'সক্রিয় সদস্য',
    dailyGoal: 'দৈনিক লক্ষ্য',
    teaGardenTheme: 'অসামের চা বাগান 🍃',
    loktakTheme: 'লোকটাক লেক 🪷',
    orientationHeader: 'দৈনিক স্মৃতি সহায়ক 📍',
    orientationSub: 'উত্তর-পূর্বাঞ্চলীয় স্থান ও সময় নির্দেশিকা',
    todaysDate: 'আজকের তারিখ ও সময়',
    currentSeason: 'বর্তমান ঋতু',
    medicationCheck: 'সকালের ওষুধ',
    medicationTaken: 'নেওয়া হয়েছে ✓',
    medicationPending: 'স্মরণ করিয়ে দেওয়া হবে 🔔',
    memoryAnchorPrompt: 'ব্যক্তিগত স্মৃতি সহায়ক',
    memoryAnchorText: 'আপনি গুয়াহাটিতে নিজের বাড়িতে আছেন। পরিবারের সাথে আজ এক শান্তিপূর্ণ দিন।',
    startExercise: 'অনুশীলন শুরু করুন',
    navDashboard: 'ড্যাশবোর্ড',
    navLeaderboard: 'লিডারবোর্ড',
    navExercises: 'জ্ঞানভিত্তিক অনুশীলন',
    navTelemetry: 'এআই স্বাস্থ্য নিরীক্ষণ',
    navPath: 'জ্ঞানভিত্তিক পথ',
    navMetrics: 'মেট্রিক ও ট্রেন্ড',
    navGarden: '৩ডি স্মৃতি বাগান',
    navCaregiver: 'কেয়ারগিভার পোর্টাল',
    streak: 'স্ট্রীক',
    level: 'লেভেল',
    rank: 'র‍্যাঙ্ক',
    audioOn: 'অডিও অন',
    audioOff: 'অডিও অফ',
    patientView: 'রোগীর ভিউ',
    caregiverView: 'কেয়ারগিভার ভিউ',
    logout: 'লগআউট',
    readAnchorAloud: 'শব্দ করে পড়ুন',
    water3dGarden: '৩ডি বাগানে জল দিন 💦',
    vrMode: 'ভিআর মোড 👓'
  },
  mni: {
    platformTitle: 'মেমোমেট — অৱাং নোংপোক্ষেন জ্ঞানাশ্রম',
    dementiaSubtitle: 'অৱাং নোংপোক্ষেনগী অহল ওইরবশিংগী নিংশিং থৌনা সহায়ক',
    goodMorning: 'আয়ুক অমুক',
    goodAfternoon: 'নুংথিল অমুক',
    goodEvening: 'নুমিদাং অমুক',
    goodNight: 'অহিং অমুক',
    activeMember: 'অহল মেম্বর',
    dailyGoal: 'নুমিৎসিগী পান্দম',
    teaGardenTheme: 'অসাম চাহ বাগিচা 🍃',
    loktakTheme: 'লোকটাক পাৎ 🪷',
    orientationHeader: 'নুমিৎসিগী নিংশিং সহায়ক 📍',
    orientationSub: 'অৱাং নোংপোক্ষেন মফম নিংশিং থৌনা',
    todaysDate: 'ঙসিগী তারিখ অমসুং মাতম',
    currentSeason: 'হৌজিক ওইরিবা ঋতু',
    medicationCheck: 'আয়ুকগী হিদাং',
    medicationTaken: 'চাখ্রে ✓',
    medicationPending: 'নিংশিংহনবা 🔔',
    memoryAnchorPrompt: 'ইশাগী নিংশিং সহায়ক',
    memoryAnchorText: 'অদোম ইম্ফালদা ইমুংগা লোয়ননা লাইবাক ফব নুমিৎনি।',
    startExercise: 'হৌদোকউ',
    navDashboard: 'ড্যাশবোর্ড',
    navLeaderboard: 'লিডারবোর্ড',
    navExercises: 'জ্ঞানভিত্তিক অনুশীলন',
    navTelemetry: 'এআই হেল্থ',
    navPath: 'জ্ঞানভিত্তিক লম্বী',
    navMetrics: 'মেট্রিক অমসুং ট্রেন্দ',
    navGarden: '৩ডি স্মৃতি বাগান',
    navCaregiver: 'কেয়ারগিভার পোর্টাল',
    streak: 'স্ট্রীক',
    level: 'লেভেল',
    rank: 'র‍্যাঙ্ক',
    audioOn: 'অডিও অন',
    audioOff: 'অডিও অফ',
    patientView: 'রোগীর ভিউ',
    caregiverView: 'কেয়ারগিভার ভিউ',
    logout: 'লগআউট',
    readAnchorAloud: 'পাবিয়ু',
    water3dGarden: 'ইশিং থানবা 💦',
    vrMode: 'ভিআর মোড 👓'
  },
  kha: {
    platformTitle: 'MemoMate — NER Dementia Platform',
    dementiaSubtitle: 'AI Cognitive Assistance for Elderly Dementia Patients in Meghalaya & NER',
    goodMorning: 'Khyndai Mynstep',
    goodAfternoon: 'Khein Mynsngi',
    goodEvening: 'Khein Mynstep',
    goodNight: 'Mynmiet Bha',
    activeMember: 'ACTIVE MEMBER',
    dailyGoal: 'DAILY GOAL',
    teaGardenTheme: 'Assam Tea Garden 🍃',
    loktakTheme: 'Loktak Floating Meadow 🪷',
    orientationHeader: 'Dementia Daily Memory Anchor 📍',
    orientationSub: 'North Eastern Region Location & Memory Assistance',
    todaysDate: "Today's Date & Time",
    currentSeason: 'Current Season in Meghalaya',
    medicationCheck: 'Morning Medicine',
    medicationTaken: 'Taken ✓',
    medicationPending: 'Reminder 🔔',
    memoryAnchorPrompt: 'Personal Memory Anchor',
    memoryAnchorText: 'You are in Shillong, Meghalaya. Surrounded by family in a peaceful home.',
    startExercise: 'START EXERCISE',
    navDashboard: 'Dashboard',
    navLeaderboard: 'Leaderboard',
    navExercises: 'Cognitive Exercises',
    navTelemetry: 'AI Health Telemetry',
    navPath: 'Cognitive Path',
    navMetrics: 'Metrics & Trends',
    navGarden: '3D Memory Garden',
    navCaregiver: 'Caregiver Portal',
    streak: 'Streak',
    level: 'Level',
    rank: 'Rank',
    audioOn: 'AUDIO ON',
    audioOff: 'AUDIO OFF',
    patientView: 'Patient View',
    caregiverView: 'Caregiver View',
    logout: 'Logout',
    readAnchorAloud: 'READ ALOUD',
    water3dGarden: 'WATER 3D GARDEN 💦',
    vrMode: 'TOGGLE VR MODE 👓'
  },
  hi: {
    platformTitle: 'मेमोमेट — उत्तर-पूर्वी क्षेत्र संज्ञानात्मक मंच',
    dementiaSubtitle: 'उत्तर-पूर्वी भारत (NER) के बुजुर्ग डिमेंशिया रोगियों के लिए एआई स्मृति सहायता प्लेटफॉर्म',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    goodNight: 'शुभ रात्रि',
    activeMember: 'सक्रिय सदस्य',
    dailyGoal: 'दैनिक लक्ष्य',
    teaGardenTheme: 'असम चाय बागान 🍃',
    loktakTheme: 'लोकटक तैरती झील 🪷',
    orientationHeader: 'डिमेंशिया दैनिक स्मृति अंकुश 📍',
    orientationSub: 'उत्तर-पूर्वी क्षेत्र स्थान और स्मृति सहायता',
    todaysDate: 'आज की तिथि और समय',
    currentSeason: 'वर्तमान ऋतु',
    medicationCheck: 'सुबह की दवा',
    medicationTaken: 'ली गई ✓',
    medicationPending: 'रिमाइंडर 🔔',
    memoryAnchorPrompt: 'व्यक्तिगत स्मृति अंकुश',
    memoryAnchorText: 'आप गुवाहाटी में अपने घर पर हैं। परिवार के साथ आज एक शांतिपूर्ण दिन है।',
    startExercise: 'अभ्यास शुरू करें',
    navDashboard: 'डैशबोर्ड',
    navLeaderboard: 'लीडरबोर्ड',
    navExercises: 'संज्ञानात्मक अभ्यास',
    navTelemetry: 'एआई स्वास्थ्य टेलीमेट्री',
    navPath: 'संज्ञानात्मक पथ',
    navMetrics: 'मीट्रिक और रुझान',
    navGarden: '3D स्मृति उद्यान',
    navCaregiver: 'केयरगिवर पोर्टल',
    streak: 'स्ट्रिक',
    level: 'स्तर',
    rank: 'रैंक',
    audioOn: 'ऑडियो ऑन',
    audioOff: 'ऑडियो ऑफ',
    patientView: 'रोगी दृश्य',
    caregiverView: 'केयरगिवर दृश्य',
    logout: 'लॉगआउट',
    readAnchorAloud: 'स्मृति अंकुश सुनें',
    water3dGarden: '3D बगीचे में पानी दें 💦',
    vrMode: 'वीआर मोड बदलें 👓'
  }
};
