export const NER_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🌐' },
  { code: 'hi', name: 'हिन्दी (Hindi)', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ் (Tamil)', flag: '🏛️' },
  { code: 'te', name: 'తెలుగు (Telugu)', flag: '🏺' },
  { code: 'kn', name: 'கன்னட / ಕನ್ನಡ (Kannada)', flag: '🐘' },
  { code: 'ml', name: 'മലയാളം (Malayalam)', flag: '🌴' },
  { code: 'mr', name: 'मराठी (Marathi)', flag: '🏰' },
  { code: 'bn', name: 'বাংলা (Bengali)', flag: '⛵' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)', flag: '🪷' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)', flag: '🌾' },
  { code: 'or', name: 'ଓଡ଼ିଆ (Odia)', flag: '🪁' },
  { code: 'as', name: 'অসমীয়া (Assamese)', flag: '🍃' },
  { code: 'mni', name: 'মৈতৈলোન્ (Manipuri)', flag: '🌸' },
  { code: 'kha', name: 'Khasi (Meghalaya)', flag: '⛰️' }
];

export const NER_TRANSLATIONS = {
  en: {
    platformTitle: 'MemoMate — Cognitive Gaming Platform',
    dementiaSubtitle: 'AI-Based Cognitive Gaming & Memory Assistance Platform',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    goodNight: 'Good Night',
    activeMember: 'COGNITIVE MEMBER',
    dailyGoal: 'DAILY COGNITIVE GOAL',
    orientationHeader: 'Daily Memory Anchor',
    orientationSub: 'Location & Daily Memory Assistance',
    todaysDate: "Today's Date & Time",
    currentSeason: 'Current Season',
    medicationCheck: 'Morning Medication',
    medicationTaken: 'Taken ✓',
    medicationPending: 'Pending Reminder',
    memoryAnchorPrompt: 'Personal Memory Anchor',
    memoryAnchorText: 'You are at home surrounded by loved ones. Today is a peaceful day for mental wellness.',
    startExercise: 'START EXERCISE NOW',
    navHome: 'Home',
    navPlay: 'Play',
    navMyDay: 'My Day',
    navMyMemories: 'My Memories',
    navDashboard: 'Dashboard',
    navLeaderboard: 'Leaderboard',
    navExercises: 'Cognitive Exercises',
    navTelemetry: 'AI Health Telemetry',
    navPath: 'Cognitive Path',
    navMetrics: 'Metrics & Trends',
    navGarden: 'Memory Garden',
    navCaregiver: 'Caregiver Portal',
    talkToMemoMate: 'Talk to MemoMate',
    startTodaysActivity: "START TODAY'S ACTIVITY",
    whyMemoMateChoseThis: 'Why did MemoMate choose this?',
    todaysSchedule: "Today's Schedule & Reminders",
    todaysMemoryStory: "Today's Memory Story",
    myPeopleTitle: 'My People & Family Memories',
    addFamilyMember: 'Add Family Member',
    nerCulturalTitle: 'North Eastern Cultural Memories',
    offlineStatusOnline: 'ONLINE',
    offlineStatusOffline: 'OFFLINE',
    offlineStatusSyncing: 'SYNCING',
    themeLabel: 'Theme:',
    themeNature: 'Calm Nature',
    themeSunrise: 'Sunrise',
    themeForest: 'Forest',
    themeOcean: 'Ocean',
    themeLavender: 'Lavender',
    themeHighContrast: 'High Contrast',
    themeHealthcare: 'Healthcare Warm',
    themeFirePro: 'Pro Gamified Fire',
    themeDaylight: 'Soft Daylight',
    notAssessed: 'Not assessed',
    letsBuildProfile: "Let's build your cognitive profile",
    baselinePromptSub: 'Complete a 2-minute baseline assessment to measure your starting point.',
    startBaseline: 'START BASELINE ASSESSMENT',
    beginBaseline: 'BEGIN ASSESSMENT',
    profileReady: 'Your initial cognitive profile is ready!',
    goToDashboard: 'GO TO MY DASHBOARD',
    hereIsYourDay: 'Here is your cognitive day with MemoMate.',
    letsUnderstandStarting: "Let's establish your cognitive baseline profile today.",
    masterTier: 'Master Tier',
    optimal: 'Optimal',
    consistent: 'Consistent',
    focusArea: 'Focus Area',
    streak: 'Streak',
    level: 'Level',
    rank: 'Rank',
    audioOn: 'AUDIO ON',
    audioOff: 'AUDIO OFF',
    patientView: 'Patient View',
    caregiverView: 'Caregiver View',
    logout: 'Logout',
    readAnchorAloud: 'READ ALOUD',
    water3dGarden: 'CHARGING NEURAL MATRIX',
    vrMode: 'TOGGLE VR MODE',
    memoryScore: 'Memory Index',
    attentionScore: 'Focus & Attention',
    recallScore: 'Recall Speed',
    reactionScore: 'Reaction Time',
    overallScore: 'Overall Performance',
    dailyQuests: 'Daily Cognitive Quests',
    claimReward: 'Claim Reward',
    completed: 'Completed',
    inProgress: 'In Progress',
    relicsShop: 'Cognitive Relics & Rewards Store',
    leaderboardTitle: 'Global Cognitive Leaderboard',
    recentActivity: 'Live Community Feed',
    quickStart: 'Recommended Training Mission',
    streakCount: 'Day Streak',
    checkinToday: 'Complete Module to Maintain Streak',
    alreadyChecked: 'Daily Exercise Completed 🔥',
    liveActivityTitle: 'Live Activity Stream',
    liveActivitySub: 'Real-Time Community Exercise Feed',
    liveSync: 'Live Sync',
    syncingActivity: 'Syncing activity stream...',
    noActivityYet: 'No Live Community Activities Yet',
    noActivitySub: 'Be the first community member to complete an exercise session to kick off the real-time activity stream!',
    completedAction: 'completed',
    justNow: 'Just now',
    mAgo: 'm ago',
    hAgo: 'h ago',
    dAgo: 'd ago',
    cognitiveMetricsHeader: 'Current Cognitive Profile & Metrics',
    streakArenaTitle: 'Daily Streak Arena',
    streakShield: 'STREAK SHIELD ACTIVE',
    weeklyCalendar: 'WEEKLY CHECKIN CALENDAR',
    xpMultiplierText: '1.25x XP MULTIPLIER ACTIVE! Play daily exercises to maintain your streak.',
    recordCheckin: 'RECORD DAILY CHECKIN',
    resetsAtMidnight: 'RESETS AT MIDNIGHT • EARN GEMS & XP',
    quest1Title: 'Complete 2 Cognitive Missions',
    quest2Title: 'Score over 80 in Focus Reflex',
    quest3Title: 'Maintain your Daily Workout Streak',
    adaptiveMission: 'ADAPTIVE AI BATTLE MISSION',
    aiTelemetry: 'GROQ LLAMA-3 AI TELEMETRY',
    focusMissionTitle: 'FOCUS MISSION:',
    startBattleMission: 'START BATTLE MISSION',
    missionBonusSub: '⚡ Completing this mission earns +100 XP, unlocks Battle Gems & expands your 3D Garden.',
    leaderboardSub: 'TOP ACTIVE MEMBERS • REAL-TIME STANDINGS',
    viewLeaderboard: 'VIEW LEADERBOARD',
    topDivision: 'TOP DIVISION',
    you: '(You)',
    daysStreak: 'd streak',
    shopSub: 'REDEEM POINTS FOR POWER-UPS & CYBER AVATARS',
    unlockFor: 'UNLOCK FOR',
    unlocked: 'UNLOCKED ✓',
    cognitivePathTitle: 'PERSONALIZED COGNITIVE PATH',
    gardenSub: 'REAL-TIME 3D VISUALIZATION OF NEURAL RELICS',
    cyberCrystals: 'CYBER CRYSTALS',
    neuralCores: 'NEURAL CORES',
    quantumRings: 'QUANTUM RINGS',
    openMindSanctum: 'OPEN MIND SANCTUM',
    morningSessionActive: 'MORNING SESSION ACTIVE',
    morningSessionSub: 'Peak mental acuity window. Execute short-term memory drills and 3D spatial focus exercises.',
    afternoonSessionActive: 'PEAK MIND PERFORMANCE',
    afternoonSessionSub: 'Sustain maximum processing speed with mid-day 3D target search and reaction challenges.',
    eveningSessionActive: 'EVENING RECALL SESSION',
    eveningSessionSub: 'Unwind with pattern recall, Mind Matrix expansion, and cognitive exercises.',
    nightSessionActive: 'MEMORY CONSOLIDATION',
    nightSessionSub: 'Rest supports neural synaptic consolidation. Outstanding cognitive progress completed today!',
    dailyGoalTier: 'DAILY GOAL TIER',
    progress: 'PROGRESS',
    currentReward: 'CURRENT REWARD: 3D QUANTUM CRYSTAL',
    nextTier: 'NEXT TIER: HEROIC CREST (+150 PTS)',
    dailyProgram: 'DAILY PROGRAM',
    league: 'LEAGUE',
    days: 'DAYS',
    navMenu: 'NAVIGATION MENU',
    cognitiveCare: 'COGNITIVE CARE',
    sidebarTip: 'Complete daily exercises to maintain your streak & unlock Mind Matrix rewards.',
    navExternalGamification: 'Gamification Hub',
    externalGamificationTag: 'DEDICATED GAMIFICATION HUB 🌐',
    externalGamificationTitle: 'External Cognitive Gamification Portal',
    configurePortal: 'Configure Link',
    launchGamificationBtn: 'OPEN EXTERNAL GAMIFICATION APP 🚀',
    startGame: 'START GAME',
    spatialMazeTitle: 'Spatial Maze Navigator',
    spatialMazeDesc: 'Procedural 2D/3D orientation and spatial navigation maze challenge for elderly memory training.',
    spatialOrientationCategory: 'Spatial Orientation',
    newDynamicBadge: 'NEW DYNAMIC',
    toneRhythmTitle: 'Acoustic Rhythm & Tone Recall',
    toneRhythmDesc: 'Interactive audio-visual harmonic tone sequence recall game with dynamic pattern scaling.',
    auditoryMemoryCategory: 'Auditory Memory',
    spatialNodeTitle: 'Spatial Node Matrix',
    spatialNodeDesc: 'Interactive 3D Three.js WebGL Quantum Node flip game with procedural color pairs.',
    memoryMatrixCategory: '3D Memory Matrix',
    dynamic3dBadge: 'DYNAMIC 3D',
    targetFocusTitle: '3D Target Focus Search',
    targetFocusDesc: 'Interactive 3D Target Search using Three.js raycasting to find target quantum crystals.',
    targetPrecisionCategory: 'Target Precision',
    quantumSpeedTitle: 'Quantum Speed Reflex',
    quantumSpeedDesc: 'Orbiting WebGL 3D Target Orbs measuring real-time spatial reaction speed in milliseconds.',
    reactionSpeedCategory: 'Reaction Speed',
    focusReflexTitle: 'Focus Reflex & Math Matrix',
    focusReflexDesc: 'Procedural focus and mental calculation challenges scaling dynamically with your level.',
    executiveFocusCategory: 'Executive Focus',
    proceduralBadge: 'PROCEDURAL',
    cardMatchTitle: 'Card Memory Matrix',
    cardMatchDesc: 'Procedurally generated card matching game to train visual recall and concentration.',
    visualMemoryCategory: 'Visual Memory',
    speedReactionTitle: 'Speed Reflex Reaction Test',
    speedReactionDesc: 'Motor reaction speed test measuring response velocity in milliseconds.',
    motorSpeedCategory: 'Motor Speed',
    numberRecallGameTitle: '3D Dual-N-Back & Number Recall',
    numberRecallGameDesc: 'Procedural digit sequence memorization scaling from 3 to 10 digits based on progress.',
    sequenceRecallCategory: 'Sequence Recall',
    holographicTitle: '3D Holographic Matrix',
    holographicDesc: '3D grid matrix of illuminated WebGL cubes to reinforce spatial pattern recognition.',
    patternMemoryCategory: 'Pattern Memory',
    wordRecallTitle: '3D Categorical Word Recall',
    wordRecallDesc: 'Revolving 3D Three.js WebGL word spheres for multi-category item recall.',
    categoricalRecallCategory: 'Categorical Recall',
    movesTaken: 'MOVES TAKEN',
    timeElapsed: 'TIME ELAPSED',
    sequenceRound: 'SEQUENCE ROUND',
    cognitiveScore: 'COGNITIVE SCORE',
    roundsPassed: 'ROUNDS PASSED',
    mazeSolved: 'MAZE SOLVED SUCCESSFULLY!',
    tryAgain: 'TRY AGAIN',
    playAgainMaze: 'PLAY AGAIN (NEW PROCEDURAL MAZE)',
    autumnSeason: 'Autumn / Post-Monsoon 🌿',
    springSeason: 'Spring / Renewal 🌸',
    summerSeason: 'Summer / Warmth ☀️',
    winterSeason: 'Winter / Calm ❄️',
    pleasantClimate: 'Pleasant climate for cognitive wellness',
    exportReport: 'Export Summary Report',
    selectMonitoredPatient: 'SELECT MONITORED PATIENT',
    improvingStatus: 'Improving',
    focusNeededStatus: 'Focus Needed',
    consistentStatus: 'Consistent',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    backToExercises: '← Back to Exercise Hub',
    performanceAnalysis: 'Performance Analysis',
    adaptiveRecommendationEngine: 'Adaptive Recommendation Engine',
    caregiverMonitoring: 'Caregiver Portal & Clinical Monitoring',
    externalGamificationDesc: 'Launch external Unity 3D cognitive WebGL worlds and multiplayer brain training arenas.',
    cyberRelicCategory: '3D Cyber Relic',
    quantumCrystalTitle: 'Quantum Crystal Relic',
    quantumCrystalDesc: 'Unlocks dynamic glowing 3D quantum crystals in your interactive Mind Matrix Sanctum.',
    telemetryPowerupCategory: 'AI Telemetry Power-Up',
    neuralBoosterTitle: 'Neural Core Booster',
    neuralBoosterDesc: 'Boosts cognitive analysis precision with instant AI neural telemetry.',
    battleShieldCategory: 'Battle Shield',
    streakShieldTitle: 'Streak Freeze Shield',
    streakShieldDesc: 'Protects your daily workout streak for 1 day if a session is missed.',
    profileAvatarCategory: 'Profile Avatar',
    heroicCrestTitle: 'Heroic Memory Crest',
    heroicCrestDesc: 'Displays legendary Heroic rank aura on profile & global leaderboard.',
    lockedBtn: 'LOCKED (EARN GEMS)',
    textNormal: 'Normal',
    textLarge: 'Large',
    textExtraLarge: 'Extra Large',
    textSizeLabel: 'Text Size:',
    voiceAssistanceOn: 'Voice Assistance ON',
    voiceAssistanceOff: 'Voice Assistance OFF',
    patientRole: 'Patient',
    ageSuffix: 'yrs',
    levelInitiate: 'Level 1: Cognitive Initiate ⚡',
    orbitGuide: '🖱️ Drag to orbit 3D Sanctum • Scroll to zoom',
    mission1Completed: '1 Mission Completed',
    activatesCyberCrystal: 'Activates Cyber Crystal (+100 XP)',
    coreInnovationBadge: 'Core Innovation',
    personalizedPathTitle: 'Personalized Cognitive Path 🌱',
    personalizedPathDesc: 'AI tailored progress path based on clinical assessments and daily performance.',
    todaysGentleEncouragement: "TODAY'S GENTLE ENCOURAGEMENT 🌱",
    startToneRecall: '▷ START TONE RECALL EXERCISE',
    cyanColor: 'CYAN',
    emeraldColor: 'EMERALD',
    goldColor: 'GOLD',
    purpleColor: 'PURPLE',
    matchedPairs: 'MATCHED',
    welcomeBack: 'Welcome Back',
    signInSub: 'Sign in with your registered email and password',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    signInBtn: 'Sign In',
    authenticating: 'Authenticating...',
    noAccountText: "Don't have an account?",
    registerNowLink: 'Register Now',
    createAccount: 'Create Account',
    registerSub: 'Register your official profile on MemoMate database',
    fullNameLabel: 'Full Name',
    ageLabel: 'Age',
    accountRoleLabel: 'Account Role',
    preferredLangLabel: 'Preferred Language',
    confirmPasswordLabel: 'Confirm Password',
    creatingAccount: 'Creating Account...',
    registerAccountBtn: 'Register Account',
    alreadyRegisteredText: 'Already registered?',
    logInHereLink: 'Log in here',
    logInWithThisAccount: 'Log in with this account →',
    enterEmailPassword: 'Please enter your email address and password',
    invalidEmailPassword: 'Invalid email or password.',
    valNameReq: 'Full Name is required',
    valEmailReq: 'Email address is required',
    valEmailInvalid: 'Please enter a valid email address',
    valPassReq: 'Password is required',
    valPassMin: 'Password must be at least 6 characters long',
    valPassMismatch: 'Passwords do not match',
    regFailed: 'Registration failed. Email may already be registered.',
    caregiverRole: 'Caregiver',
    voiceTitle: 'Talk to MemoMate',
    voiceSub: 'Voice AI Assistant',
    voiceTapToSpeak: 'Tap to Speak',
    voiceListening: 'Listening...',
    voiceProcessing: 'Understanding your question...',
    voiceSpeaking: 'Responding...',
    voiceError: 'Could not hear clearly. Please try again.',
    voiceNoSupport: 'Speech recognition is not supported on this browser.',
    voiceNoLanguageVoice: 'Voice audio is unavailable for this language on this device. Displaying text response.',
    voicePromptInitial: 'Hello! How can I help you today?',
    voiceResponseTodayActivity: "Today you should complete your cognitive memory exercises. Shall we start now?",
    voiceResponseHowAreYou: 'I am doing well! Ready to help you exercise your memory today.',
    voiceResponseGames: 'We have Memory Match, Focus Reflex, Number Recall, Pattern Recall, and 3D Target Search. Which one would you like to play?',
    voiceResponseFallback: "I am here to support your mental wellness every day. You can ask about today's activities, games, or medication reminders.",
    voiceBtnYesStart: 'Yes, Start Now',
    voiceBtnLater: 'Later',
    pts: 'PTS',
    startMissionNow: 'START MISSION NOW',
    excellentRecall: 'EXCELLENT RECALL!',
    missionComplete: 'MISSION COMPLETE!',
    playAgain: 'PLAY AGAIN',
    scoreMessage: 'Score: {score} / 100 PTS',
    completedInMoves: 'Completed in {moves} moves',
    roundInfo: 'ROUND {round} / {total}',
    scoreText: 'SCORE: {score}',
    correctFeedback: 'Correct! +{points} pts ({time}ms)',
    wrongFeedback: 'Wrong! Correct answer: {answer}',
    matched: 'Matched',
    moves: 'Moves',
    findSymbolPrompt: 'Find the Symbol: {symbol}'
  },
  hi: {
    platformTitle: 'मेमोमेट — संज्ञानात्मक गेमिंग प्लेटफॉर्म',
    dementiaSubtitle: 'एआई-आधारित संज्ञानात्मक गेमिंग और स्मृति सहायता प्लेटफॉर्म',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    goodNight: 'शुभ रात्रि',
    activeMember: 'संज्ञानात्मक सदस्य',
    dailyGoal: 'दैनिक संज्ञानात्मक लक्ष्य',
    orientationHeader: 'दैनिक स्मृति अंकुश 📍',
    orientationSub: 'स्थान और दैनिक स्मृति सहायता',
    todaysDate: 'आज की तिथि और समय',
    currentSeason: 'वर्तमान ऋतु',
    medicationCheck: 'सुबह की दवा',
    medicationTaken: 'ली गई ✓',
    medicationPending: 'रिमाइंडर 🔔',
    memoryAnchorPrompt: 'व्यक्तिगत स्मृति अंकुश',
    memoryAnchorText: 'आप अपने परिवार के साथ घर पर हैं। आज मानसिक स्वास्थ्य के लिए एक शांतिपूर्ण दिन है।',
    startExercise: 'अभ्यास शुरू करें',
    navDashboard: 'डैशबोर्ड',
    navLeaderboard: 'लीडरबोर्ड',
    navExercises: 'संज्ञानात्मक अभ्यास',
    navTelemetry: 'एआई स्वास्थ्य टेलीमेट्री',
    navPath: 'संज्ञानात्मक पथ',
    navMetrics: 'मीट्रिक और रुझान',
    navGarden: 'माइंड मैट्रिक्स',
    navCaregiver: 'केयरगिवर पोर्टल',
    streak: 'स्ट्रिक',
    level: 'स्तर',
    rank: 'रैंक',
    audioOn: 'ऑडियो ऑन',
    audioOff: 'ऑडियो ऑफ',
    patientView: 'रोगी दृश्य',
    caregiverView: 'केयरगिवर दृश्य',
    logout: 'लॉगआउट',
    readAnchorAloud: 'सुनें',
    water3dGarden: 'न्यूरल मैट्रिक्स चार्ज करें ⚡',
    vrMode: 'वीआर मोड बदलें 👓',
    memoryScore: 'स्मृति सूचकांक',
    attentionScore: 'ध्यान और एकाग्रता',
    recallScore: 'स्मरण गति',
    reactionScore: 'प्रतिक्रिया समय',
    overallScore: 'कुल प्रदर्शन',
    dailyQuests: 'दैनिक संज्ञानात्मक कार्य',
    claimReward: 'पुरस्कार प्राप्त करें',
    completed: 'पूर्ण',
    inProgress: 'प्रगति पर',
    relicsShop: 'पुरस्कार स्टोर',
    leaderboardTitle: 'ग्लोबल लीडरबोर्ड',
    recentActivity: 'लाइव समुदाय फ़ीड',
    quickStart: 'अनुशंसित प्रशिक्षण',
    streakCount: 'दिनों की स्ट्रिक',
    checkinToday: 'स्ट्रिक बनाए रखने के लिए मॉड्यूल पूरा करें',
    alreadyChecked: 'दैनिक अभ्यास पूरा हुआ 🔥',
    backToExercises: '← अभ्यासों पर वापस जाएं',
    performanceAnalysis: 'प्रदर्शन विश्लेषण',
    adaptiveRecommendationEngine: 'अनुकूली अनुशंसा इंजन',
    caregiverMonitoring: 'केयरगिवर पोर्टल और नैदानिक ​​निगरानी',
    externalGamificationDesc: 'बाहरी 3D संज्ञानात्मक दुनिया शुरू करें।',
    cyberRelicCategory: '3D साइबर अवशेष',
    quantumCrystalTitle: 'क्वांटम क्रिस्टल अवशेष',
    quantumCrystalDesc: 'माइंड सैंक्टम के लिए 3D क्रिस्टल खोलें।',
    telemetryPowerupCategory: 'एआई पावर-अप',
    neuralBoosterTitle: 'न्यूरल कोर बूस्टर',
    neuralBoosterDesc: 'त्वरित एआई विश्लेषण सटीकता बढ़ाएं।',
    battleShieldCategory: 'सुरक्षा ढाल',
    streakShieldTitle: 'स्ट्रिक फ्रीज शील्ड',
    streakShieldDesc: '1 दिन छूटने पर भी स्ट्रिक की रक्षा करें।',
    profileAvatarCategory: 'प्रोफ़ाइल अवतार',
    heroicCrestTitle: 'हीरोइक मेमोरी क्रेस्ट',
    heroicCrestDesc: 'लीडरबोर्ड पर हीरोइक बैज प्रदर्शित करें।',
    lockedBtn: 'लॉक (रत्न कमाएं)',
    textNormal: 'सामान्य',
    textLarge: 'बड़ा',
    textExtraLarge: 'बहुत बड़ा',
    textSizeLabel: 'फ़ॉन्ट आकार:',
    voiceAssistanceOn: 'ध्वनि सहायता चालू',
    voiceAssistanceOff: 'ध्वनि सहायता बंद',
    patientRole: 'रोगी',
    ageSuffix: 'वर्ष',
    levelInitiate: 'स्तर 1: संज्ञानात्मक शुरुआत ⚡',
    orbitGuide: '🖱️ 3D दृश्य घुमाने के लिए ड्रैग करें',
    mission1Completed: '1 मिशन पूरा हुआ',
    activatesCyberCrystal: 'साइबर क्रिस्टल सक्रिय करता है (+100 XP)',
    coreInnovationBadge: 'मुख्य नवाचार',
    personalizedPathTitle: 'व्यक्तिगत संज्ञानात्मक पथ 🌱',
    personalizedPathDesc: 'नैदानिक ​​मूल्यांकन पर आधारित एआई पथ।',
    todaysGentleEncouragement: 'आज का कोमल प्रोत्साहन 🌱',
    startToneRecall: '▷ टोन रिकॉल अभ्यास शुरू करें',
    cyanColor: 'स्यान',
    emeraldColor: 'पन्ना',
    goldColor: 'गोल्ड',
    purpleColor: 'बैंगनी',
    matchedPairs: 'मिलाया गया',
    welcomeBack: 'वापसी पर स्वागत है',
    signInSub: 'अपने पंजीकृत ईमेल और पासवर्ड से साइन इन करें',
    emailLabel: 'ईमेल पता',
    passwordLabel: 'पासवर्ड',
    signInBtn: 'साइन इन करें',
    authenticating: 'प्रमाणित हो रहा है...',
    noAccountText: 'खाता नहीं है?',
    registerNowLink: 'अभी पंजीकरण करें',
    createAccount: 'खाता बनाएं',
    registerSub: 'मेमोमेट डेटाबेस पर अपना प्रोफ़ाइल पंजीकृत करें',
    fullNameLabel: 'पूरा नाम',
    ageLabel: 'आयु',
    accountRoleLabel: 'खाता भूमिका',
    preferredLangLabel: 'पसंदीदा भाषा',
    confirmPasswordLabel: 'पासवर्ड की पुष्टि करें',
    creatingAccount: 'खाता बनाया जा रहा है...',
    registerAccountBtn: 'खाता पंजीकृत करें',
    alreadyRegisteredText: 'पहले से पंजीकृत हैं?',
    logInHereLink: 'यहाँ लॉग इन करें',
    logInWithThisAccount: 'इस खाते से लॉग इन करें →',
    enterEmailPassword: 'कृपया अपना ईमेल पता और पासवर्ड दर्ज करें',
    invalidEmailPassword: 'अमान्य ईमेल या पासवर्ड।',
    valNameReq: 'पूरा नाम आवश्यक है',
    valEmailReq: 'ईमेल पता आवश्यक है',
    valEmailInvalid: 'कृपया एक मान्य ईमेल पता दर्ज करें',
    valPassReq: 'पासवर्ड आवश्यक है',
    valPassMin: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
    valPassMismatch: 'पासवर्ड मेल नहीं खाते',
    regFailed: 'पंजीकरण विफल रहा। ईमेल पहले से पंजीकृत हो सकता है।',
    caregiverRole: 'केयरगिवर',
    voiceTitle: 'मेमोमेट से बात करें',
    voiceSub: 'वॉयस एआई सहायक',
    voiceTapToSpeak: 'बोलने के लिए दबाएं',
    voiceListening: 'सुन रहा हूँ...',
    voiceProcessing: 'आपके प्रश्न को समझ रहा हूँ...',
    voiceSpeaking: 'उत्तर दे रहा हूँ...',
    voiceError: 'स्पष्ट रूप से नहीं सुन सका। कृपया पुनः प्रयास करें।',
    voiceNoSupport: 'इस ब्राउज़र में भाषण पहचान समर्थित नहीं है।',
    voiceNoLanguageVoice: 'इस डिवाइस पर हिंदी आवाज उपलब्ध नहीं है। पाठ दिखाया जा रहा है।',
    voicePromptInitial: 'नमस्ते! आज मैं आपकी कैसे मदद कर सकता हूँ?',
    voiceResponseTodayActivity: 'आज आपको अपने संज्ञानात्मक स्मृति अभ्यासों को पूरा करना चाहिए। क्या हम अभी शुरू करें?',
    voiceResponseHowAreYou: 'मैं ठीक हूँ! आज आपकी स्मृति का अभ्यास कराने के लिए तैयार हूँ।',
    voiceResponseGames: 'हमारे पास मेमोरी मैच, फोकस रिफ्लेक्स, नंबर रिकॉल, पैटर्न रिकॉल और 3D टारगेट सर्च हैं। आप कौन सा खेलना चाहेंगे?',
    voiceResponseFallback: 'मैं आपके मानसिक स्वास्थ्य का समर्थन करने के लिए प्रतिदिन यहाँ हूँ। आप आज की गतिविधियों, खेलों या दवा के रिमाइंडर्स के बारे में पूछ सकते हैं।',
    voiceBtnYesStart: 'हाँ, अभी शुरू करें',
    voiceBtnLater: 'बाद में',
    pts: 'अंक',
    startMissionNow: 'मिशन अभी शुरू करें',
    excellentRecall: 'उत्कृष्ट स्मरण शक्ति!',
    missionComplete: 'मिशन पूरा हुआ!',
    playAgain: 'फिर से खेलें',
    scoreMessage: 'स्कोर: {score} / 100 अंक',
    completedInMoves: '{moves} चालों में पूरा हुआ',
    roundInfo: 'राउंड {round} / {total}',
    scoreText: 'स्कोर: {score}',
    correctFeedback: 'सही! +{points} अंक ({time}ms)',
    wrongFeedback: 'गलत! सही उत्तर: {answer}',
    matched: 'मिलाया गया',
    moves: 'चालें',
    findSymbolPrompt: 'प्रतीक खोजें: {symbol}'
  },
  ta: {
    platformTitle: 'மெமோமேட் — அறிவாற்றல் கேமிங் தளம்',
    dementiaSubtitle: 'செயற்கை நுண்ணறிவு நினைவாற்றல் உதவி தளம்',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    goodNight: 'இரவு வணக்கம்',
    activeMember: 'அறிவாற்றல் உறுப்பினர்',
    dailyGoal: 'தினசரி அறிவாற்றல் இலக்கு',
    orientationHeader: 'தினசரி நினைவாற்றல் வழிகாட்டி 📍',
    orientationSub: 'இடம் மற்றும் தினசரி நினைவாற்றல் உதவி',
    todaysDate: 'இன்றைய தேதி மற்றும் நேரம்',
    currentSeason: 'தற்போதைய பருவம்',
    medicationCheck: 'காலை மருந்து',
    medicationTaken: 'எடுத்துக்கொள்ளப்பட்டது ✓',
    medicationPending: 'நினைவூட்டல் 🔔',
    memoryAnchorPrompt: 'தனிப்பட்ட நினைவாற்றல் உதவி',
    memoryAnchorText: 'நீங்கள் உங்கள் குடும்பத்துடன் பாதுகாப்பாக வீட்டில் இருக்கிறீர்கள்.',
    startExercise: 'பயிற்சியை தொடங்குங்கள்',
    navDashboard: 'முகப்பு',
    navLeaderboard: 'முன்னணி அட்டவணை',
    navExercises: 'அறிவாற்றல் பயிற்சிகள்',
    navTelemetry: 'AI ஆரோக்கிய கண்காணிப்பு',
    navPath: 'அறிவாற்றல் பாதை',
    navMetrics: 'புள்ளிவிவரங்கள்',
    navGarden: 'மைண்ட் மேட்ரிக்ஸ்',
    navCaregiver: 'பராமரிப்பாளர் தளம்',
    themeLabel: 'தீம்:',
    themeNature: 'அமைதியான இயற்கை',
    themeSunrise: 'சூரிய உதயம்',
    themeForest: 'காடு',
    themeOcean: 'பெருங்கடல்',
    themeLavender: 'லாவெண்டர்',
    themeHighContrast: 'உயர் மாறுபாடு',
    notAssessed: 'மதிப்பிடப்படவில்லை',
    letsBuildProfile: 'உங்கள் அறிவாற்றல் சுயவிவரத்தை உருவாக்குவோம்',
    baselinePromptSub: 'தொடக்கப் புள்ளியை அளவிட 2 நிமிட மதிப்பீட்டை முடிக்கவும்.',
    startBaseline: 'தொடக்க மதிப்பீட்டைத் தொடங்கு',
    beginBaseline: 'மதிப்பீட்டைத் தொடங்கு',
    profileReady: 'உங்கள் முதல் அறிவாற்றல் சுயவிவரம் தயார்!',
    goToDashboard: 'எனது முகப்பிற்குச் செல்',
    hereIsYourDay: 'மெமோமேட்டுடன் இன்றைய நாள்.',
    letsUnderstandStarting: 'இன்று உங்கள் அறிவாற்றல் தொடக்க நிலையை நிறுவுவோம்.',
    masterTier: 'முக்கிய நிலை',
    optimal: 'சிறந்த நிலை',
    consistent: 'சீரான நிலை',
    focusArea: 'கவனப் பகுதி',
    streak: 'தொடர்ச்சி (Streak)',
    level: 'நிலை',
    rank: 'தரவரிசை',
    audioOn: 'ஒலி ஆன்',
    audioOff: 'ஒலி ஆஃப்',
    patientView: 'நோயாளி பார்வை',
    caregiverView: 'பராமரிப்பாளர் பார்வை',
    logout: 'வெளியேறு',
    readAnchorAloud: 'சத்தமாக வாசிக்கவும்',
    water3dGarden: 'நியூரல் மேட்ரிக்ஸ் சார்ஜ் ⚡',
    vrMode: 'VR பயன்முறை 👓',
    memoryScore: 'நினைவாற்றல் குறியீடு',
    attentionScore: 'கவனம் மற்றும் செறிவூட்டல்',
    recallScore: 'நினைவுகூரும் வேகம்',
    reactionScore: 'பதிலளிப்பு நேரம்',
    overallScore: 'மொத்த செயல்திறன்',
    dailyQuests: 'தினசரி பணிகள்',
    claimReward: 'பரிசைப் பெறுங்கள்',
    completed: 'முடிந்தது',
    inProgress: 'நடைபெறுகிறது',
    relicsShop: 'பரிசுகள் அங்காடி',
    leaderboardTitle: 'உலகளாவிய முன்னணி பட்டியல்',
    recentActivity: 'நேரலை செய்திகள்',
    quickStart: 'பரிந்துரைக்கப்பட்ட பயிற்சி',
    streakCount: 'நாட்கள் தொடர்ச்சி',
    checkinToday: 'தொடர்ச்சியை பராமரிக்க பயிற்சியை முடிக்கவும்',
    alreadyChecked: 'இன்றைய பயிற்சி முடிந்தது 🔥',
    liveActivityTitle: 'நேரலை நடவடிக்கை ஸ்ட்ரீம்',
    liveActivitySub: 'நிகழ்நேர சமூக பயிற்சி ஊட்டம்',
    liveSync: 'நேரலை இணைப்பு',
    syncingActivity: 'செயல்பாடுகள் இணைக்கப்படுகின்றன...',
    noActivityYet: 'இதுவரை நேரலை செயல்பாடுகள் இல்லை',
    noActivitySub: 'நிகழ்நேர செயல்பாட்டைத் தொடங்க முதல் பயிற்சியை முடிக்கவும்!',
    completedAction: 'முடித்தார்',
    justNow: 'இப்போது',
    mAgo: 'நிமிடம் முன்',
    hAgo: 'மணி முன்',
    dAgo: 'நாள் முன்',
    cognitiveMetricsHeader: 'தற்போதைய அறிவாற்றல் சுயவிவரம் மற்றும் அளவீடுகள்',
    streakArenaTitle: 'தினசரி தொடர்ச்சி அரங்கம்',
    streakShield: 'தொடர்ச்சி பாதுகாப்பு இயங்குகிறது',
    weeklyCalendar: 'வாராந்திர வருகை நாள்காட்டி',
    xpMultiplierText: '1.25x XP பெருக்கி இயங்குகிறது! தொடர்ச்சியைப் பராமரிக்கப் பயிற்சியை விளையாடுங்கள்.',
    recordCheckin: 'இன்றைய வருகையைப் பதிவுசெய்',
    resetsAtMidnight: 'நள்ளிரவில் புதுப்பிக்கப்படும் • ரத்தினங்கள் & XP பெறுங்கள்',
    quest1Title: '2 அறிவாற்றல் பணிகளை முடிக்கவும்',
    quest2Title: 'கவனப் பயிற்சியில் 80+ மதிப்பெண் பெறுங்கள்',
    quest3Title: 'தினசரி பயிற்சித் தொடர்ச்சியைப் பராமரிக்கவும்',
    adaptiveMission: 'தகவமைப்பு AI பயிற்சிப் பணி',
    aiTelemetry: 'GROQ LLAMA-3 AI தொலைஅளவியல்',
    focusMissionTitle: 'கவனப் பணி:',
    startBattleMission: 'பயிற்சிப் பணியைத் தொடங்கு',
    missionBonusSub: '⚡ இப்பணியை முடிப்பது +100 XP, ரத்தினங்கள் மற்றும் 3D தோட்டத்தை விரிவுபடுத்தும்.',
    leaderboardSub: 'சிறந்த உறுப்பினர்கள் • நேரலை தரவரிசை',
    viewLeaderboard: 'முன்னணி பட்டியலைக் காண்க',
    topDivision: 'உயர்மட்டப் பிரிவு',
    you: '(நீங்கள்)',
    daysStreak: 'நாட்கள் தொடர்ச்சி',
    shopSub: 'ரத்தினங்களைக் கொண்டு படிகங்களைத் திறக்கவும்',
    unlockFor: 'திறக்க',
    unlocked: 'திறக்கப்பட்டது ✓',
    cognitivePathTitle: 'தனிப்பயனாக்கப்பட்ட அறிவாற்றல் பாதை',
    gardenSub: 'நரம்பியல் வடிவங்களின் நேரலை 3D காட்சி',
    cyberCrystals: 'சைபர் படிகங்கள்',
    neuralCores: 'நரம்பு மையங்கள்',
    quantumRings: 'குவாண்டம் வளையங்கள்',
    openMindSanctum: 'மனப் பீடத்தைத் திறக்கவும்',
    morningSessionActive: 'காலை அமர்வு இயங்குகிறது',
    morningSessionSub: 'உச்ச மனத் திறன் நேரம். குறுகிய கால நினைவாற்றல் மற்றும் 3D கவனப் பயிற்சிகளைச் செய்யுங்கள்.',
    afternoonSessionActive: 'உச்ச மனச் செயல்திறன்',
    afternoonSessionSub: 'நண்பகல் 3D இலக்குத் தேடல் மற்றும் எதிர்வினைப் பயிற்சிகளுடன் செயலாக்க வேகத்தைத் தக்கவைக்கவும்.',
    eveningSessionActive: 'மாலை நினைவுகூரும் அமர்வு',
    eveningSessionSub: 'முறைமை நினைவுகூரல் மற்றும் அறிவாற்றல் பயிற்சிகளுடன் மாலையைத் தொடங்குங்கள்.',
    nightSessionActive: 'நினைவாற்றல் ஒருங்கிணைப்பு',
    nightSessionSub: 'ஓய்வு நரம்பியல் நினைவாற்றலை வலுப்படுத்துகிறது. இன்று சிறந்த முன்னேற்றம் அடைந்துள்ளீர்கள்!',
    dailyGoalTier: 'தினசரி இலக்கு நிலை',
    progress: 'முன்னேற்றம்',
    currentReward: 'தற்போதைய பரிசு: 3D குவாண்டம் படிகம்',
    nextTier: 'அடுத்த நிலை: வீர் முத்திரை (+150 PTS)',
    dailyProgram: 'தினசரி திட்டம்',
    league: 'லீக்',
    days: 'நாட்கள்',
    navMenu: 'வழிசெலுத்தல் மெனு',
    cognitiveCare: 'அறிவாற்றல் பராமரிப்பு',
    sidebarTip: 'தொடர்ச்சியைப் பராமரிக்கவும் பரிசுகளைத் திறக்கவும் தினசரி பயிற்சிகளை முடிக்கவும்.',
    startGame: 'விளையாட்டைத் தொடங்கு',
    spatialMazeTitle: 'இடஞ்சார்ந்த பிரமை வழிகாட்டி',
    spatialMazeDesc: 'நினைவாற்றல் மற்றும் திசை அறிவை மேம்படுத்தும் பிரமை சவால்.',
    spatialOrientationCategory: 'இடஞ்சார்ந்த திசையறிவு',
    newDynamicBadge: 'புதிய நேரலை',
    toneRhythmTitle: 'ஒலி மற்றும் இசை நினைவுகூருதல்',
    toneRhythmDesc: 'ஒலி அலைவரிசைகளை நினைவில் கொண்டு திரும்பச் செய்யும் இசைப் பயிற்சி.',
    auditoryMemoryCategory: 'கேட்கும் நினைவாற்றல்',
    spatialNodeTitle: '3D மேட்ரிக்ஸ் கணுக்கள்',
    spatialNodeDesc: '3D வண்ண இணைகளை நினைவில் வைத்து பொருத்தும் பயிற்சி.',
    memoryMatrixCategory: '3D நினைவாற்றல் மேட்ரிக்ஸ்',
    dynamic3dBadge: 'நேரலை 3D',
    targetFocusTitle: '3D இலக்கு தேடல்',
    targetFocusDesc: '3D படிகங்களை தேடி கண்டுபிடிக்கும் கவனப் பயிற்சி.',
    targetPrecisionCategory: 'இலக்கு கவனம்',
    quantumSpeedTitle: 'வேகப் பதிலளிப்பு பயிற்சி',
    quantumSpeedDesc: 'சுற்றும் 3D கோளங்களை தொட்டு பதிலளிப்பு நேரத்தை அளவிடும் பயிற்சி.',
    reactionSpeedCategory: 'பதிலளிப்பு வேகம்',
    focusReflexTitle: 'கவனப் பயிற்சி & கணித மேட்ரிக்ஸ்',
    focusReflexDesc: 'மனக் கணக்குகள் மற்றும் கவனத்தை மேம்படுத்தும் பயிற்சி.',
    executiveFocusCategory: 'முக்கிய கவனம்',
    proceduralBadge: 'தானியங்கி',
    cardMatchTitle: 'அட்டை நினைவாற்றல் மேட்ரிக்ஸ்',
    cardMatchDesc: 'காட்சி நினைவாற்றலையும் செறிவூட்டலையும் அதிகரிக்கும் அட்டைப் பொருத்தம்.',
    visualMemoryCategory: 'காட்சி நினைவாற்றல்',
    speedReactionTitle: 'வேக எதிர்வினை சோதனை',
    speedReactionDesc: 'மோட்டார் மறுமொழி வேகத்தை மில்லி விநாடிகளில் அளவிடும் பயிற்சி.',
    motorSpeedCategory: 'இயக்க வேகம்',
    numberRecallGameTitle: '3D எண்கள் நினைவுகூருதல்',
    numberRecallGameDesc: 'எண்களின் வரிசையை நினைவில் கொண்டு திரும்ப அளிக்கும் பயிற்சி.',
    sequenceRecallCategory: 'வரிசை நினைவுகூருதல்',
    holographicTitle: '3D ஹோலோகிராஃபிக் மேட்ரிக்ஸ்',
    holographicDesc: 'ஒளிரும் 3D கட்டங்களை நினைவில் கொள்ளும் வடிவப் பயிற்சி.',
    patternMemoryCategory: 'வடிவ நினைவாற்றல்',
    wordRecallTitle: '3D சொற்கள் நினைவுகூருதல்',
    wordRecallDesc: 'சுழலும் 3D சொற்களை நினைவில் கொண்டு வகைப்படுத்தும் பயிற்சி.',
    categoricalRecallCategory: 'வகைப்படுத்தல் நினைவாற்றல்',
    battlePathTitle: 'அறிவாற்றல் பாதை வரைபடம்',
    battlePathSub: 'உங்கள் அறிவாற்றல் வரிசை நிகழ்நேர மதிப்பெண்களுக்கு ஏற்ப மாறுகிறது',
    fullRoadmap: 'முழு வரைபடம் →',
    currentFocusMission: 'தற்போதைய முக்கிய பணி',
    nextStage: 'அடுத்த நிலை',
    upcomingStage: 'அடுத்தகட்ட நிலை',
    playMission: 'பணியைத் தொடங்கு',
    recommendedMissionDesc: 'AI பகுப்பாய்வின் அடிப்படையில் பரிந்துரைக்கப்பட்ட பணி',
    memoryMatchTitle: '3D நினைவாற்றல் பொருத்தம் 🎨',
    numberRecallTitle: 'எண் நினைவுகூருதல் 🔢',
    patternRecallTitle: 'வடிவ நினைவுகூருதல் 🧩',
    reactionTestTitle: 'பதிலளிப்பு வேகப் பயிற்சி ⚡',
    sessionCompletedToday: 'இன்றைய பயிற்சி நிறைவடைந்தது',
    seqMemoryDesc: 'வரிசை நினைவாற்றல் பயிற்சி',
    gridSpatialDesc: 'இடஞ்சார்ந்த நினைவாற்றல் சவால்',
    movesTaken: 'எடுத்த நகர்வுகள்',
    timeElapsed: 'எடுத்த நேரம்',
    sequenceRound: 'வரிசைச் சுற்று',
    cognitiveScore: 'அறிவாற்றல் புள்ளிகள்',
    roundsPassed: 'முடிந்த சுற்றுகள்',
    mazeSolved: 'பிரமை வெற்றி!',
    tryAgain: 'மீண்டும் முயல்க',
    playAgainMaze: 'மீண்டும் விளையாடு (புதிய பிரமை)',
    autumnSeason: 'இலையுதிர் பருவம் 🌿',
    springSeason: 'இளவேனில் பருவம் 🌸',
    summerSeason: 'கோடைப் பருவம் ☀️',
    winterSeason: 'குளிர்ப் பருவம் ❄️',
    pleasantClimate: 'மன ஆரோக்கியத்திற்கு ஏற்ற இதமான வானிலை',
    exportReport: 'அறிக்கையை பதிவிறக்கு',
    selectMonitoredPatient: 'கண்காணிக்கப்படும் நோயாளியைத் தேர்ந்தெடு',
    improvingStatus: 'முன்னேறுகிறது',
    focusNeededStatus: 'கவனம் தேவை',
    consistentStatus: 'சீரானது',
    last7Days: 'கடந்த 7 நாட்கள்',
    last30Days: 'கடந்த 30 நாட்கள்',
    backToExercises: '← பயிற்சிகளுக்குத் திரும்பு',
    performanceAnalysis: 'செயல்திறன் பகுப்பாய்வு',
    adaptiveRecommendationEngine: 'தகவமைப்புப் பரிந்துரை அமைப்பு',
    caregiverMonitoring: 'பராமரிப்பாளர் தளம் & மருத்துவ கண்காணிப்பு',
    externalGamificationDesc: 'வெளிப்புற 3D நினைவாற்றல் உலகங்களைத் தொடங்குங்கள்.',
    cyberRelicCategory: '3D சைபர் பொருள்',
    quantumCrystalTitle: 'குவாண்டம் படிகப் பொருள்',
    quantumCrystalDesc: 'மனப் பீடத்திற்கான ஒளிரும் 3D படிகங்களைத் திறக்கும்.',
    telemetryPowerupCategory: 'AI தொலைஅளவியல் பவர்-அப்',
    neuralBoosterTitle: 'நரம்பியல் மைய ஊக்கி',
    neuralBoosterDesc: 'உடனடி AI பகுப்பாய்வு திறனை அதிகரிக்கும்.',
    battleShieldCategory: 'பாதுகாப்புக் கேடயம்',
    streakShieldTitle: 'தொடர்ச்சி பாதுகாப்பு கேடயம்',
    streakShieldDesc: '1 நாள் பயிற்சி தவறினாலும் தொடர்ச்சியைப் பாதுகாக்கும்.',
    profileAvatarCategory: 'சுயவிவர அவதாரம்',
    heroicCrestTitle: 'வீர நினைவாற்றல் முத்திரை',
    heroicCrestDesc: 'முன்னணிப் பட்டியலில் வீர முத்திரையைக் காட்டும்.',
    lockedBtn: 'பூட்டப்பட்டது (ரத்தினங்கள் தேவை)',
    textNormal: 'இயல்பான',
    textLarge: 'பெரிய',
    textExtraLarge: 'மிகப் பெரிய',
    textSizeLabel: 'எழுத்து அளவு:',
    voiceAssistanceOn: 'குரல் உதவி இயங்குகிறது',
    voiceAssistanceOff: 'குரல் உதவி அணைக்கப்பட்டது',
    patientRole: 'நோயாளி',
    ageSuffix: 'வயது',
    levelInitiate: 'நிலை 1: அறிவாற்றல் தொடக்கநிலை ⚡',
    orbitGuide: '🖱️ 3D பார்வையை சுழற்ற இழுக்கவும்',
    mission1Completed: '1 பணி முடிந்தது',
    activatesCyberCrystal: 'சைபர் படிகத்தை செயல்படுத்துகிறது (+100 XP)',
    coreInnovationBadge: 'முக்கிய கண்டுபிடிப்பு',
    personalizedPathTitle: 'தனிப்பயனாக்கப்பட்ட அறிவாற்றல் பாதை 🌱',
    personalizedPathDesc: 'மருத்துவ மதிப்பீடுகள் அடிப்படையிலான AI முன்னேற்றப் பாதை.',
    todaysGentleEncouragement: 'இன்றைய அமைதியான ஊக்கம் 🌱',
    startToneRecall: '▷ ஒலி நினைவுகூரும் பயிற்சியைத் தொடங்கு',
    cyanColor: 'நீலம் (CYAN)',
    emeraldColor: 'பச்சை (EMERALD)',
    goldColor: 'மஞ்சள் (GOLD)',
    purpleColor: 'ஊதா (PURPLE)',
    matchedPairs: 'பொருந்தியது',
    welcomeBack: 'மீண்டும் வருக',
    signInSub: 'உங்கள் பதிவு செய்யப்பட்ட மின்னஞ்சல் மற்றும் கடவுச்சொல்லுடன் உள்நுழையவும்',
    emailLabel: 'மின்னஞ்சல் முகவரி',
    passwordLabel: 'கடவுச்சொல்',
    signInBtn: 'உள்நுழைக',
    authenticating: 'சரிபார்க்கிறது...',
    noAccountText: 'கணக்கு இல்லையா?',
    registerNowLink: 'இப்போதே பதிவு செய்யுங்கள்',
    createAccount: 'கணக்கை உருவாக்கு',
    registerSub: 'மெமோமேட் தரவுத்தளத்தில் உங்கள் அதிகாரப்பூர்வ சுயவிவரத்தைப் பதிவுசெய்க',
    fullNameLabel: 'முழு பெயர்',
    ageLabel: 'வயது',
    accountRoleLabel: 'கணக்கு பங்கு',
    preferredLangLabel: 'விருப்பமான மொழி',
    confirmPasswordLabel: 'கடவுச்சொல்லை உறுதிப்படுத்துக',
    creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது...',
    registerAccountBtn: 'கணக்கை பதிவு செய்',
    alreadyRegisteredText: 'ஏற்கனவே பதிவு செய்துள்ளீர்களா?',
    logInHereLink: 'இங்கே உள்நுழையவும்',
    logInWithThisAccount: 'இந்தக் கணக்கில் உள்நுழைக →',
    enterEmailPassword: 'தயவுசெய்து உங்கள் மின்னஞ்சல் முகவரி மற்றும் கடவுச்சொல்லை உள்ளிடவும்',
    invalidEmailPassword: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.',
    valNameReq: 'முழு பெயர் தேவை',
    valEmailReq: 'மின்னஞ்சல் முகவரி தேவை',
    valEmailInvalid: 'செல்லுபடியாகும் மின்னஞ்சல் முகவரியை உள்ளிடவும்',
    valPassReq: 'கடவுச்சொல் தேவை',
    valPassMin: 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்',
    valPassMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    regFailed: 'பதிவு தோல்வியடைந்தது. மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டிருக்கலாம்.',
    caregiverRole: 'பராமரிப்பாளர்',
    voiceTitle: 'மெமோமேட்டுடன் பேசுங்கள்',
    voiceSub: 'குரல் AI உதவியாளர்',
    voiceTapToSpeak: 'பேச அழுத்தவும்',
    voiceListening: 'கேட்கிறேன்...',
    voiceProcessing: 'உங்கள் கேள்வியைப் புரிந்துகொள்கிறேன்...',
    voiceSpeaking: 'பதில் அளிக்கிறேன்...',
    voiceError: 'தெளிவாக கேட்கவில்லை. மீண்டும் முயற்சிக்கவும்.',
    voiceNoSupport: 'இந்த உலாவியில் பேச்சு அங்கீகாரம் ஆதரிக்கப்படவில்லை.',
    voiceNoLanguageVoice: 'இந்த சாதனத்தில் தமிழ் குரல் வசதி கிடைக்கவில்லை. உரையாக காட்டப்படுகிறது.',
    voicePromptInitial: 'வணக்கம்! இன்று உங்களுக்கு எவ்வாறு உதவ முடியும்?',
    voiceResponseTodayActivity: 'இன்று நீங்கள் உங்கள் அறிவாற்றல் நினைவகப் பயிற்சிகளை முடிக்க வேண்டும். அதை இப்போது தொடங்கவா?',
    voiceResponseHowAreYou: 'நான் நன்றாக இருக்கிறேன்! இன்று உங்கள் நினைவாற்றலைப் பயிற்சி செய்ய உதவத் தயார்.',
    voiceResponseGames: 'என்னிடம் நினைவகப் பொருத்தம், கவனப் பயிற்சி, எண் நினைவுகூருதல், வடிவப் பயிற்சி மற்றும் 3D இலக்குத் தேடல் ஆகியவை உள்ளன. எதை விளையாட விரும்புகிறீர்கள்?',
    voiceResponseFallback: 'உங்கள் மன நலத்தை ஆதரிக்க நான் தினமும் இங்கு இருக்கிறேன். இன்றைய செயல்பாடுகள், விளையாட்டுகள் அல்லது மருந்து நினைவூட்டல்கள் பற்றி நீங்கள் கேட்கலாம்.',
    voiceBtnYesStart: 'ஆம், இப்போது தொடங்கு',
    voiceBtnLater: 'பின்னர்',
    pts: 'புள்ளிகள்',
    startMissionNow: 'பயிற்சியைத் தொடங்கு',
    excellentRecall: 'அற்புதமான நினைவாற்றல்!',
    missionComplete: 'பயிற்சி முடிந்தது!',
    playAgain: 'மீண்டும் விளையாடு',
    scoreMessage: 'மதிப்பெண்: {score} / 100 புள்ளிகள்',
    completedInMoves: '{moves} நகர்வுகளில் முடிக்கப்பட்டது',
    roundInfo: 'சுற்று {round} / {total}',
    scoreText: 'மதிப்பெண்: {score}',
    correctFeedback: 'சரி! +{points} புள்ளிகள் ({time}மி.வி)',
    wrongFeedback: 'தவறு! சரியான பதில்: {answer}',
    matched: 'பொருந்தியது',
    moves: 'நகர்வுகள்',
    findSymbolPrompt: 'சின்னத்தைக் கண்டறியவும்: {symbol}'
  },
  te: {
    platformTitle: 'మెమోమేట్ — జ్ఞాన గేమింగ్ ప్లాట్‌ఫారమ్',
    dementiaSubtitle: 'AI ఆధారిత జ్ఞాపకశక్తి సహాయక వేదిక',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    goodNight: 'శుభ రాత్రి',
    activeMember: 'జ్ఞాన సభ్యుడు',
    dailyGoal: 'రోజువారీ మైండ్ లక్ష్యం',
    orientationHeader: 'రోజువారీ జ్ఞాపకశక్తి గైడ్ 📍',
    orientationSub: 'స్థానం మరియు రోజువారీ జ్ఞాపకశక్తి సహాయం',
    todaysDate: 'నేటి తేదీ మరియు సమయం',
    currentSeason: 'ప్రస్తుత కాలం',
    medicationCheck: 'ఉదయం మందులు',
    medicationTaken: 'తీసుకున్నారు ✓',
    medicationPending: 'రిమైండర్ 🔔',
    memoryAnchorPrompt: 'వ్యక్తిగత జ్ఞాపకశక్తి మార్గదర్శి',
    memoryAnchorText: 'మీరు మీ కుటుంబ సభ్యులతో సురక్షితంగా ఇంట్లో ఉన్నారు.',
    startExercise: 'వ్యాయామం ప్రారంభించండి',
    navDashboard: 'డాష్‌బోర్డ్',
    navLeaderboard: 'లీడర్‌బోర్డ్',
    navExercises: 'జ్ఞాన వ్యాయామాలు',
    navTelemetry: 'AI హెల్త్ టెలిమెట్రీ',
    navPath: 'జ్ఞాన మార్గం',
    navMetrics: 'ట్రెండ్స్ & మెట్రిక్స్',
    navGarden: 'మైండ్ మ్యాట్రిక్స్',
    navCaregiver: 'కేర్‌గివర్ పోర్టల్',
    streak: 'స్ట్రీక్ (Streak)',
    level: 'స్థాయి',
    rank: 'ర్యాంక్',
    audioOn: 'ఆడియో ఆన్',
    audioOff: 'ఆడియో ఆఫ్',
    patientView: 'పేషెంట్ వ్యూ',
    caregiverView: 'కేర్‌గివర్ వ్యూ',
    logout: 'లాగ్‌అవుట్',
    readAnchorAloud: 'చదవండి',
    water3dGarden: 'ఛార్జ్ మ్యాట్రిక్స్ ⚡',
    vrMode: 'VR మోడ్ 👓',
    memoryScore: 'జ్ఞాపకశక్తి స్కోర్',
    attentionScore: 'అవధానం & దృష్టి',
    recallScore: 'గుర్తుతెచ్చుకునే వేగం',
    reactionScore: 'స్పందన సమయం',
    overallScore: 'మొత్తం పనితీరు',
    dailyQuests: 'రోజువారీ లక్ష్యాలు',
    claimReward: 'బహుమతి పొందండి',
    completed: 'పూర్తయింది',
    inProgress: 'కొనసాగుతోంది',
    relicsShop: 'రివార్డ్స్ స్టోర్',
    leaderboardTitle: 'గ్లోబల్ లీడర్‌బోర్డ్',
    recentActivity: 'లైవ్ కమ్యూనిటీ ఫీడ్',
    quickStart: 'సిఫార్సు చేసిన శిక్షణ',
    streakCount: 'రోజుల స్ట్రీక్',
    checkinToday: 'స్ట్రీక్ కొనసాగించడానికి వ్యాయామం చేయండి',
    alreadyChecked: 'నేటి వ్యాయామం పూర్తయింది 🔥'
  },
  kn: {
    platformTitle: 'ಮೆಮೊಮೇಟ್ — ಜ್ಞಾನ ಗೇಮಿಂಗ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್',
    dementiaSubtitle: 'ಎಐ ಆಧಾರಿತ ನೆನಪಿನ ಶಕ್ತಿ ನೆರವು ವೇದಿಕೆ',
    goodMorning: 'শুভೋದಯ / ಸುಪ್ರಭಾತ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    goodNight: 'ಶುಭ ರಾತ್ರಿ',
    activeMember: 'ಜ್ಞಾನ ಸದಸ್ಯ',
    dailyGoal: 'ದೈನಂದಿನ ಮಾನಸಿಕ ಗುರಿ',
    orientationHeader: 'ದೈನಂದಿನ ನೆನಪಿನ ಶಕ್ತಿ ಮಾರ್ಗದರ್ಶಿ 📍',
    orientationSub: 'ಸ್ಥಳ ಮತ್ತು ದೈನಂದಿನ ನೆನಪಿನ ಸಹಾಯ',
    todaysDate: 'ಇಂದಿನ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ',
    currentSeason: 'ಪ್ರಸ್ತುತ ಋತು',
    medicationCheck: 'ಬೆಳಗಿನ ಔಷಧಿ',
    medicationTaken: 'ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ ✓',
    medicationPending: 'ಜ್ಞಾಪನೆ 🔔',
    memoryAnchorPrompt: 'ವೈಯಕ್ತಿಕ ನೆನಪಿನ ಮಾರ್ಗದರ್ಶಿ',
    memoryAnchorText: 'ನೀವು ನಿಮ್ಮ ಕುಟುಂಬದೊಂದಿಗೆ ಮನೆಯಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿದ್ದೀರಿ.',
    startExercise: 'ಅಭ್ಯಾಸ ಪ್ರಾರಂಭಿಸಿ',
    navDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    navLeaderboard: 'ಲೀಡರ್‌ಬೋರ್ಡ್',
    navExercises: 'ಜ್ಞಾನಾತ್ಮಕ ಅಭ್ಯಾಸಗಳು',
    navTelemetry: 'ಎಐ ಆರೋಗ್ಯ ತಂತ್ರಜ್ಞಾನ',
    navPath: 'ಜ್ಞಾನ ಪಥ',
    navMetrics: 'ವಿಶ್ಲೇಷಣೆ',
    navGarden: 'ಮೈಂಡ್ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    navCaregiver: 'ಪಾಲನೆದಾರರ ಪೋರ್ಟಲ್',
    streak: 'ಸ್ಟ್ರೀಕ್',
    level: 'ಮಟ್ಟ',
    rank: 'ಶ್ರೇಣಿ',
    audioOn: 'ಆಡಿಯೋ ಆನ್',
    audioOff: 'ಆಡಿಯೋ ಆಫ್',
    patientView: 'ರೋಗಿಯ ನೋಟ',
    caregiverView: 'ಪಾಲನೆದಾರರ ನೋಟ',
    logout: 'ಲಾಗ್‌ಔಟ್',
    readAnchorAloud: 'ಓದಿ',
    water3dGarden: 'ಮ್ಯಾಟ್ರಿಕ್ಸ್ ಚಾರ್ಜ್ ಮಾಡಿ ⚡',
    vrMode: 'VR ಮೋಡ್ 👓',
    memoryScore: 'ನೆನಪಿನ ಸೂಚ್ಯಂಕ',
    attentionScore: 'ಗಮನ ಮತ್ತು ಏಕಾಗ್ರತೆ',
    recallScore: 'ನೆನಪಿಸಿಕೊಳ್ಳುವ ವೇಗ',
    reactionScore: 'ಪ್ರತಿಕ್ರಿಯಾ ಸಮಯ',
    overallScore: 'ಒಟ್ಟು ಸಾಧನೆ',
    dailyQuests: 'ದೈನಂದಿನ ಕಾರ್ಯಗಳು',
    claimReward: 'ಬಹುಮಾನ ಪಡೆಯಿರಿ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    relicsShop: 'ಬಹುಮಾನಗಳ ಅಂಗಡಿ',
    leaderboardTitle: 'ಜಾಗತಿಕ ಶ್ರೇಣಿ ಪಟ್ಟಿ',
    recentActivity: 'ಲೈವ್ ಫೀಡ್',
    quickStart: 'ಶಿಫಾರಸು ಮಾಡಿದ ಅಭ್ಯಾಸ',
    streakCount: 'ದಿನಗಳ ಸ್ಟ್ರೀಕ್',
    checkinToday: 'ಸ್ಟ್ರೀಕ್ ಕಾಯ್ದುಕೊಳ್ಳಲು ಅಭ್ಯಾಸ ಪೂರ್ಣಗೊಳಿಸಿ',
    alreadyChecked: 'ಇಂದಿನ ಅಭ್ಯಾಸ ಪೂರ್ಣಗೊಂಡಿದೆ 🔥'
  },
  ml: {
    platformTitle: 'മെമോമേറ്റ് — ബോധശേഷി ഗെയിമിംഗ് പ്ലാറ്റ്‌ഫോം',
    dementiaSubtitle: 'എഐ അധിഷ്ഠിത ഓർമ്മശക്തി സഹായ പ്ലാറ്റ്‌ഫോം',
    goodMorning: 'സുപ്രഭാതം',
    goodAfternoon: 'ശുഭ ഉച്ചസമയം',
    goodEvening: 'ശുഭ സായാഹ്നം',
    goodNight: 'ശുഭ രാത്രി',
    activeMember: 'അംഗം',
    dailyGoal: 'ദൈനംദിന ലക്ഷ്യം',
    orientationHeader: 'ഓർമ്മ സഹായി 📍',
    orientationSub: 'സ്ഥലവും ഓർമ്മ പുതുക്കലും',
    todaysDate: 'ഇന്നത്തെ തീയതിയും സമയവും',
    currentSeason: 'ഇപ്പോഴത്തെ സമയം',
    medicationCheck: 'രാവിലത്തെ മരുന്ന്',
    medicationTaken: 'കഴിച്ചു ✓',
    medicationPending: 'ഓർമ്മപ്പെടുത്തൽ 🔔',
    memoryAnchorPrompt: 'വ്യക്തിഗത ഓർമ്മ സഹായി',
    memoryAnchorText: 'നിങ്ങൾ കുടുംബത്തോടൊപ്പം വീട്ടിൽ സുരക്ഷിതമായിരിക്കുന്നു.',
    startExercise: 'പരിശീലനം ആരംഭിക്കുക',
    navDashboard: 'ഡാഷ്‌ബോർഡ്',
    navLeaderboard: 'ലീഡർബോർഡ്',
    navExercises: 'പരിശീലനങ്ങൾ',
    navTelemetry: 'എഐ ഹെൽത്ത്',
    navPath: 'വഴി',
    navMetrics: 'വിശകലനം',
    navGarden: 'മൈൻഡ് മാട്രിക്സ്',
    navCaregiver: 'പരിപാലക പോർട്ടൽ',
    streak: 'സ്ട്രീക (Streak)',
    level: 'ലെവൽ',
    rank: 'റാങ്ക്',
    audioOn: 'ഓഡിയോ ഓൺ',
    audioOff: 'ഓഡിയോ ഓഫ്',
    patientView: 'രോഗിയുടെ കാഴ്ച',
    caregiverView: 'പരിപാലക കാഴ്ച',
    logout: 'ലോഗ് ഔട്ട്',
    readAnchorAloud: 'വായിക്കുക',
    water3dGarden: 'ചാർജ് മാട്രിക്സ് ⚡',
    vrMode: 'VR മോഡ് 👓',
    memoryScore: 'ഓർമ്മശക്തി സ്കോർ',
    attentionScore: 'ശ്രദ്ധയും ഏകാഗ്രതയും',
    recallScore: 'ഓർത്തെടുക്കൽ വേഗത',
    reactionScore: 'പ്രതികരണ സമയം',
    overallScore: 'ആകെ പ്രകടനം',
    dailyQuests: 'ദൈനംദിന ദൗത്യങ്ങൾ',
    claimReward: 'സമ്മാനം നേടുക',
    completed: 'പൂർത്തിയായി',
    inProgress: 'പുരോഗമിക്കുന്നു',
    relicsShop: 'റിവാർഡ് സ്റ്റോർ',
    leaderboardTitle: 'ഗ്ലോബൽ ലീഡർബോർഡ്',
    recentActivity: 'ലൈവ് ഫീഡ്',
    quickStart: 'നിർദ്ദേശിച്ച പരിശീലനം',
    streakCount: 'ദിന സ്ട്രീക്',
    checkinToday: 'സ്ട്രീക നിലനിർത്താൻ പരിശീലനം ചെയ്യുക',
    alreadyChecked: 'ഇന്നത്തെ പരിശീലനം പൂർത്തിയായി 🔥'
  },
  mr: {
    platformTitle: 'मेमोमेट — संज्ञानात्मक गेमिंग प्लॅटफॉर्म',
    dementiaSubtitle: 'एआय-आधारित स्मरणशक्ती आणि संज्ञानात्मक सहाय्य प्लॅटफॉर्म',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    goodNight: 'शुभ रात्री',
    activeMember: 'संज्ञानात्मक सदस्य',
    dailyGoal: 'दैनिक ध्येय',
    orientationHeader: 'दैनिक स्मरणशक्ती मार्गदर्शक 📍',
    orientationSub: 'स्थान आणि दैनिक स्मरण सहाय्य',
    todaysDate: 'आजची तारीख आणि वेळ',
    currentSeason: 'सध्याचा ऋतू',
    medicationCheck: 'सकाळचे औषध',
    medicationTaken: 'घेतले ✓',
    medicationPending: 'स्मरणपत्र 🔔',
    memoryAnchorPrompt: 'वैयक्तिक स्मरण मार्गदर्शक',
    memoryAnchorText: 'तुम्ही तुमच्या कुटुंबासोबत घरी सुरक्षित आहात.',
    startExercise: 'सराव सुरू करा',
    navDashboard: 'डॅशबोर्ड',
    navLeaderboard: 'लीडरबोर्ड',
    navExercises: 'संज्ञानात्मक सराव',
    navTelemetry: 'एआय आरोग्य ट्रॅकिंग',
    navPath: 'संज्ञानात्मक मार्ग',
    navMetrics: 'आकडेवारी',
    navGarden: 'माइंड मॅट्रिक्स',
    navCaregiver: 'केअरगिव्हर पोर्टल',
    streak: 'स्ट्रिक (Streak)',
    level: 'पातळी',
    rank: 'रँक',
    audioOn: 'ऑडिओ ऑन',
    audioOff: 'ऑडिओ ऑफ',
    patientView: 'रुग्ण दृश्य',
    caregiverView: 'केअरगिव्हर दृश्य',
    logout: 'लॉगआउट',
    readAnchorAloud: 'वाचा',
    water3dGarden: 'मॅट्रिक्स चार्ज करा ⚡',
    vrMode: 'VR मोड 👓',
    memoryScore: 'स्मरणशक्ती निर्देशांक',
    attentionScore: 'एकाग्रता आणि लक्ष',
    recallScore: 'आठवण्याचा वेग',
    reactionScore: 'प्रतिक्रिया वेळ',
    overallScore: 'एकूण कामगिरी',
    dailyQuests: 'दैनिक कार्ये',
    claimReward: 'बक्षीस मिळवा',
    completed: 'पूर्ण',
    inProgress: 'प्रगतीपथावर',
    relicsShop: 'बक्षीस स्टोअर',
    leaderboardTitle: 'ग्लोबल लीडरबोर्ड',
    recentActivity: 'थेट समुदाय फीड',
    quickStart: 'शीर्ष सराव',
    streakCount: 'दिवसांची स्ट्रिक',
    checkinToday: 'स्ट्रिक टिकवण्यासाठी सराव करा',
    alreadyChecked: 'आजचा सराव पूर्ण झाला 🔥'
  },
  bn: {
    platformTitle: 'মেমোমেট — জ্ঞানভিত্তিক গেমিং প্ল্যাটফর্ম',
    dementiaSubtitle: 'এআই-ভিত্তিক স্মৃতিশক্তি ও জ্ঞানভিত্তিক সহায়তা প্ল্যাটফর্ম',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপরাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    goodNight: 'শুভ রাত্রি',
    activeMember: 'সক্রিয় সদস্য',
    dailyGoal: 'দৈনিক লক্ষ্য',
    orientationHeader: 'দৈনিক স্মৃতি সহায়ক 📍',
    orientationSub: 'অবস্থান ও দৈনন্দিন স্মৃতি গাইড',
    todaysDate: 'আজকের তারিখ ও সময়',
    currentSeason: 'বর্তমান ঋতু',
    medicationCheck: 'সকালের ওষুধ',
    medicationTaken: 'নেওয়া হয়েছে ✓',
    medicationPending: 'স্মরণ করিয়ে দেওয়া হবে 🔔',
    memoryAnchorPrompt: 'ব্যক্তিগত স্মৃতি সহায়ক',
    memoryAnchorText: 'আপনি পরিবার এবং প্রিয়জনদের সাথে নিজের বাড়িতে আছেন।',
    startExercise: 'অনুশীলন শুরু করুন',
    navDashboard: 'ড্যাশবোর্ড',
    navLeaderboard: 'লিডারবোর্ড',
    navExercises: 'জ্ঞানভিত্তিক অনুশীলন',
    navTelemetry: 'এআই স্বাস্থ্য নিরীক্ষণ',
    navPath: 'জ্ঞানভিত্তিক পথ',
    navMetrics: 'মেট্রিক ও ট্রেন্ড',
    navGarden: 'মাইন্ড ম্যাট্রিক্স',
    navCaregiver: 'কেয়ারগিভার পোর্টাল',
    streak: 'স্ট্রীক',
    level: 'লেভেল',
    rank: 'র‍্যাঙ্ক',
    audioOn: 'অডিও অন',
    audioOff: 'অডিও অফ',
    patientView: 'রোগীর ভিউ',
    caregiverView: 'কেয়ারগিভার ভিউ',
    logout: 'লগআউট',
    readAnchorAloud: 'শব্দ করে পড়ুন',
    water3dGarden: 'ম্যাট্রিক্স চার্জ করুন ⚡',
    vrMode: 'ভিআর মোড 👓',
    memoryScore: 'স্মৃতি সূচক',
    attentionScore: 'মনোযোগ ও একাগ্রতা',
    recallScore: 'স্মরণ করার গতি',
    reactionScore: 'প্রতিক্রিয়া সময়',
    overallScore: 'মোট পারফরম্যান্স',
    dailyQuests: 'দৈনিক মিশন',
    claimReward: 'পুরস্কার সংগ্রহ করুন',
    completed: 'সম্পন্ন',
    inProgress: 'চলমান',
    relicsShop: 'রিওয়ার্ড শপ',
    leaderboardTitle: 'গ্লোবাল লিডারবোর্ড',
    recentActivity: 'লাইভ কমিউনিটি ফিড',
    quickStart: 'সুপারিশকৃত অনুশীলন',
    streakCount: 'দিনের স্ট্রীক',
    checkinToday: 'স্ট্রীক বজায় রাখতে অনুশীলন সম্পন্ন করুন',
    alreadyChecked: 'আজকের অনুশীলন সম্পন্ন হয়েছে 🔥'
  },
  gu: {
    platformTitle: 'મેમોમેટ — જ્ઞાનાત્મક ગેમિંગ પ્લેટફોર્મ',
    dementiaSubtitle: 'એઆઈ-આધારિત મેમરી અને જ્ઞાનાત્મક સહાય પ્લેટફોર્મ',
    goodMorning: 'શુભ સવાર',
    goodAfternoon: 'શુભ બપોર',
    goodEvening: 'શુભ સાંજ',
    goodNight: 'શુભ રાત્રિ',
    activeMember: 'સક્રિય સભ્ય',
    dailyGoal: 'દૈનિક લક્ષ્ય',
    orientationHeader: 'દૈનિક મેમરી માર્ગદર્શક 📍',
    orientationSub: 'સ્થાન અને દૈનિક યાદશક્તિ સહાય',
    todaysDate: 'આજની તારીખ અને સમય',
    currentSeason: 'વર્તમાન ઋતુ',
    medicationCheck: 'સવારની દવા',
    medicationTaken: 'લીધી ✓',
    medicationPending: 'યાદ અપાવવું 🔔',
    memoryAnchorPrompt: 'વ્યક્તિગત યાદ માર્ગદર્શક',
    memoryAnchorText: 'તમે તમારા પરિવાર સાથે સુરક્ષિત ઘરે છો.',
    startExercise: 'કસરત શરૂ કરો',
    navDashboard: 'ડૅશબોર્ડ',
    navLeaderboard: 'લીડરબોર્ડ',
    navExercises: 'જ્ઞાનાત્મક કસરતો',
    navTelemetry: 'એઆઈ હેલ્થ ટ્રેકિંગ',
    navPath: 'જ્ઞાનાત્મક માર્ગ',
    navMetrics: 'આંકડા',
    navGarden: 'માઇન્ડ મેટ્રિક્સ',
    navCaregiver: 'કેરગીવર પોર્ટલ',
    streak: 'સ્ટ્રીક (Streak)',
    level: 'લેવલ',
    rank: 'રેન્ક',
    audioOn: 'ઑડિઓ ઑન',
    audioOff: 'ઑડિઓ ઑફ',
    patientView: 'દર્દી નો દેખાવ',
    caregiverView: 'સંભાળક નો દેખાવ',
    logout: 'લૉગ આઉટ',
    readAnchorAloud: 'વાંચો',
    water3dGarden: 'મેટ્રિક્સ ચાર્જ કરો ⚡',
    vrMode: 'VR મોડ 👓',
    memoryScore: 'યાદશક્તિ સ્કોર',
    attentionScore: 'ધ્યાન અને એકાગ્રતા',
    recallScore: 'યાદ કરવાનો વેગ',
    reactionScore: 'પ્રતિક્રિયા સમય',
    overallScore: 'કુલ પ્રદર્શન',
    dailyQuests: 'દૈનિક કાર્યો',
    claimReward: 'ઇનામ મેળવો',
    completed: 'પૂર્ણ',
    inProgress: 'ચાલુ છે',
    relicsShop: 'ઇનામ સ્ટોર',
    leaderboardTitle: 'ગ્લોબલ લીડરબોર્ડ',
    recentActivity: 'લાઈવ ફીડ',
    quickStart: 'ભલામણ કરેલ કસરત',
    streakCount: 'દિવસોની સ્ટ્રીક',
    checkinToday: 'સ્ટ્રીક જાળવવા કસરત પૂરી કરો',
    alreadyChecked: 'આજની કસરત પૂરી થઈ 🔥'
  },
  pa: {
    platformTitle: 'ਮੈਮੋਮੇਟ — ਗਿਆਨ-ਆਧਾਰਿਤ ਗੇਮਿੰਗ ਪਲੇਟਫਾਰਮ',
    dementiaSubtitle: 'ਏਆਈ-ਆਧਾਰਿਤ ਯਾਦਦਾਸ਼ਤ ਅਤੇ ਦਿਮਾਗੀ ਸਹਾਇਤਾ ਪਲੇਟਫਾਰਮ',
    goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
    goodAfternoon: 'ਸ਼ੁਭ ਦੁਪਹਿਰ',
    goodEvening: 'ਸ਼ੁਭ ਸ਼ਾਮ',
    goodNight: 'ਸ਼ੁਭ ਰਾਤ',
    activeMember: 'ਮੈਂਬਰ',
    dailyGoal: 'ਰੋਜ਼ਾਨਾ ਨਿਸ਼ਾਨਾ',
    orientationHeader: 'ਰੋਜ਼ਾਨਾ ਯਾਦਦਾਸ਼ਤ ਗਾਈਡ 📍',
    orientationSub: 'ਸਥਾਨ ਅਤੇ ਰੋਜ਼ਾਨਾ ਸਹਾਇਤਾ',
    todaysDate: 'ਅੱਜ ਦੀ ਮਿਤੀ ਅਤੇ ਸਮਾਂ',
    currentSeason: 'ਮੌਜੂਦਾ ਮੌਸਮ',
    medicationCheck: 'ਸਵੇਰ ਦੀ ਦਵਾਈ',
    medicationTaken: 'ਲਈ ਗਈ ✓',
    medicationPending: 'ਯਾਦ-ਦਹਾਨੀ 🔔',
    memoryAnchorPrompt: 'ਨਿੱਜੀ ਯਾਦ ਗਾਈਡ',
    memoryAnchorText: 'ਤੁਸੀਂ ਆਪਣੇ ਪਰਿਵਾਰ ਨਾਲ ਸੁਖੀ ਘਰ ਵਿੱਚ ਹੋ।',
    startExercise: 'ਅਭਿਆਸ ਸ਼ੁਰੂ ਕਰੋ',
    navDashboard: 'ਡੈਸ਼ਬੋਰਡ',
    navLeaderboard: 'ਲੀਡਰਬੋਰਡ',
    navExercises: 'ਦਿਮਾਗੀ ਅਭਿਆਸ',
    navTelemetry: 'ਏਆਈ ਹੈਲਥ ਟ੍ਰੈਕਿੰਗ',
    navPath: 'ਗਿਆਨ ਮਾਰਗ',
    navMetrics: 'ਰਿਪੋਰਟਾਂ',
    navGarden: 'ਮਾਈਂਡ ਮੈਟ੍ਰਿਕਸ',
    navCaregiver: 'ਦੇਖਭਾਲਕਰਤਾ ਪੋਰਟਲ',
    streak: 'ਸਟ੍ਰੀਕ (Streak)',
    level: 'ਲੇਵਲ',
    rank: 'ਰੈਂਕ',
    audioOn: 'ਆਡੀਓ ਆਨ',
    audioOff: 'ਆਡੀਓ ਆਫ',
    patientView: 'ਮਰੀਜ਼ ਵਿਊ',
    caregiverView: 'ਦੇਖਭਾਲਕਰਤਾ ਵਿਊ',
    logout: 'ਲੌਗਆਊਟ',
    readAnchorAloud: 'ਪੜ੍ਹੋ',
    water3dGarden: 'ਮੈਟ੍ਰਿਕਸ ਚਾਰਜ ਕਰੋ ⚡',
    vrMode: 'VR ਮੋਡ 👓',
    memoryScore: 'ਯਾਦਦਾਸ਼ਤ ਸਕੋਰ',
    attentionScore: 'ਧਿਆਨ ਅਤੇ ਇਕਾਗਰਤਾ',
    recallScore: 'ਯਾਦ ਕਰਨ ਦੀ ਗਤੀ',
    reactionScore: 'ਪ੍ਰਤੀਕਿਰਿਆ ਸਮਾਂ',
    overallScore: 'ਕੁੱਲ ਪ੍ਰਦਰਸ਼ਨ',
    dailyQuests: 'ਰੋਜ਼ਾਨਾ ਕੰਮ',
    claimReward: 'ਇਨਾਮ ਲਵੋ',
    completed: 'ਪੂਰਾ',
    inProgress: 'ਜਾਰੀ ਹੈ',
    relicsShop: 'ਇਨਾਮ ਸਟੋਰ',
    leaderboardTitle: 'ਗਲੋਬਲ ਲੀਡਰਬੋਰਡ',
    recentActivity: 'ਲਾਇਵ ਫੀਡ',
    quickStart: 'ਸਿਫਾਰਸ਼ੀ ਅਭਿਆਸ',
    streakCount: 'ਦਿਨਾਂ ਦੀ ਸਟ੍ਰੀਕ',
    checkinToday: 'ਸਟ੍ਰੀਕ ਬਣਾਏ ਰੱਖਣ ਲਈ ਅਭਿਆਸ ਪੂਰਾ ਕਰੋ',
    alreadyChecked: 'ਅੱਜ ਦਾ ਅਭਿਆਸ ਪੂਰਾ ਹੋਇਆ 🔥'
  },
  or: {
    platformTitle: 'ମେମୋମେଟ୍ — ଜ୍ଞାନ ଆଧାରିତ ଗେମିଂ ପ୍ଲାଟଫର୍ମ',
    dementiaSubtitle: 'ଏଆଇ-ଆଧାରିତ ସ୍ମୃତିଶକ୍ତି ଓ ମାନସିକ ସହାୟତା ପ୍ଲାଟଫର୍ମ',
    goodMorning: 'ଶୁଭ ସକାଳ',
    goodAfternoon: 'ଶୁଭ ମଧ୍ୟାହ୍ନ',
    goodEvening: 'ଶୁଭ ସନ୍ଧ୍ୟା',
    goodNight: 'ଶୁଭ ରାତ୍ରି',
    activeMember: 'ସଦସ୍ୟ',
    dailyGoal: 'ଦୈନନ୍ଦିନ ଲକ୍ଷ୍ୟ',
    orientationHeader: 'ଦୈନନ୍ଦିନ ସ୍ମୃତି ମାର୍ଗଦର୍ଶକ 📍',
    orientationSub: 'ସ୍ଥାନ ଓ ଦୈନନ୍ଦିନ ସହାୟତା',
    todaysDate: 'ଆଜିର ତାରିଖ ଓ ସମୟ',
    currentSeason: 'ବର୍ତ୍ତମାନର ଋତୁ',
    medicationCheck: 'ସକାଳର ଔଷଧ',
    medicationTaken: 'ନିଆଯାଇଛି ✓',
    medicationPending: 'ମନେପକାଇବା 🔔',
    memoryAnchorPrompt: 'ବ୍ୟକ୍ତିଗତ ସ୍ମୃତି ସହାୟକ',
    memoryAnchorText: 'ଆପଣ ନିଜ ପରିବାର ସହିତ ସୁରକ୍ଷିତ ଘରେ ଅଛନ୍ତି।',
    startExercise: 'ଅଭ୍ୟାସ ଆରମ୍ଭ କରନ୍ତୁ',
    navDashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    navLeaderboard: 'ଲିଡରବୋର୍ଡ',
    navExercises: 'ମାନସିକ ଅଭ୍ୟାସ',
    navTelemetry: 'ଏଆଇ ସ୍ୱାସ୍ଥ୍ୟ ଟ୍ରାକିଂ',
    navPath: 'ଜ୍ଞାନ ପଥ',
    navMetrics: 'ରିପୋର୍ଟ',
    navGarden: 'ମାଇଣ୍ଡ ମ୍ୟାଟ୍ରିକ୍ସ',
    navCaregiver: 'ଯତ୍ନ ନେଉଥିବା ପୋର୍ଟାଲ',
    streak: 'ଷ୍ଟ୍ରିକ୍ (Streak)',
    level: 'ସ୍ତର',
    rank: 'ର‍୍ୟାଙ୍କ',
    audioOn: 'ଅଡିଓ ଅନ୍',
    audioOff: 'ଅଡିଓ ଅଫ୍',
    patientView: 'ରୋଗୀ ଦୃଶ୍ୟ',
    caregiverView: 'ଯତ୍ନ ନେଉଥିବା ଦୃଶ୍ୟ',
    logout: 'ଲଗଆଉଟ୍',
    readAnchorAloud: 'ପଢ଼ନ୍ତୁ',
    water3dGarden: 'ମ୍ୟାଟ୍ରିକ୍ସ ଚାର୍ଜ କରନ୍ତୁ ⚡',
    vrMode: 'VR ମୋଡ୍ 👓',
    memoryScore: 'ସ୍ମୃତିସୂଚକ',
    attentionScore: 'ଧ୍ୟାନ ଓ ଏକାଗ୍ରତା',
    recallScore: 'ମନେପକାଇବା ବେଗ',
    reactionScore: 'ପ୍ରତିକ୍ରିୟା ସମୟ',
    overallScore: 'ସମୋଟ ପ୍ରଦର୍ଶନ',
    dailyQuests: 'ଦୈନନ୍ଦିନ କାର୍ଯ୍ୟ',
    claimReward: 'ପୁରସ୍କାର ନିଅନ୍ତୁ',
    completed: 'ସମ୍ପୂର୍ଣ୍ଣ',
    inProgress: 'ଚାଲୁଅଛି',
    relicsShop: 'ପୁରସ୍କାର ଷ୍ଟୋର',
    leaderboardTitle: 'ଗ୍ଲୋବାଲ ଲିଡରବୋର୍ଡ',
    recentActivity: 'ଲାଇଭ୍ ଫିଡ୍',
    quickStart: 'ସୁପାରିଶ କରାଯାଇଥିବା ଅଭ୍ୟାସ',
    streakCount: 'ଦିନର ଷ୍ଟ୍ରିକ୍',
    checkinToday: 'ଷ୍ଟ୍ରିକ୍ ବଜାୟ ରଖିବାକୁ ଅଭ୍ୟାସ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
    alreadyChecked: 'ଆଜିର ଅଭ୍ୟାସ ସମ୍ପୂର୍ଣ୍ଣ ହେଲା 🔥'
  },
  as: {
    platformTitle: 'মেমোমেট — জ্ঞানভিত্তিক প্লেটফৰ্ম',
    dementiaSubtitle: 'স্মৰণ আৰু জ্ঞানভিত্তিক সহায়ক প্লেটফৰ্ম',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপৰাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    goodNight: 'শুভ ৰাত্ৰি',
    activeMember: 'সক্ৰিয় সদস্য',
    dailyGoal: 'দৈনিক লক্ষ্য',
    orientationHeader: 'দৈনিক স্মৃতি সহায়ক 📍',
    orientationSub: 'অৱস্থান নিৰ্দেশনা আৰু স্মৃতি সহায়',
    todaysDate: 'আজিৰ তাৰিখ আৰু সময়',
    currentSeason: 'বৰ্তমান ঋতু',
    medicationCheck: 'ৰাতিপুৱাৰ ঔষধ',
    medicationTaken: 'গ্ৰহণ কৰা হ’ল ✓',
    medicationPending: 'মনত পেলোৱা হ’ব 🔔',
    memoryAnchorPrompt: 'ব্যক্তিগত স্মৃতি সহায়ক',
    memoryAnchorText: 'আপুনি নিজ গৃহত আছে। পৰিয়ালৰ সৈতে আজি এক সুন্দর দিন।',
    startExercise: 'অনুশীলন আৰম্ভ কৰক',
    navDashboard: 'ড্যাশবৰ্ড',
    navLeaderboard: 'লিডাৰবৰ্ড',
    navExercises: 'জ্ঞানভিত্তিক অনুশীলন',
    navTelemetry: 'এআই স্বাস্থ্য নিৰীক্ষণ',
    navPath: 'জ্ঞানভিত্তিক পথ',
    navMetrics: 'মেট্ৰিক আৰু ট্ৰেন্ড',
    navGarden: 'মাাইণ্ড মেট্ৰিক্স',
    navCaregiver: 'যত্নলোৱা পৰ্টেল',
    streak: 'ষ্ট্ৰীক',
    level: 'স্তৰ',
    rank: 'ৰংক',
    audioOn: 'শব্দ অন',
    audioOff: 'শব্দ অফ',
    patientView: 'ৰোগীৰ দৰ্শন',
    caregiverView: 'যত্নলোৱাৰ দৰ্শন',
    logout: 'লগআউট',
    readAnchorAloud: 'শব্দ কৰি পঢ়ক',
    water3dGarden: 'মেট্ৰিক্স চাজ কৰক ⚡',
    vrMode: 'ভিআৰ মোড 👓',
    memoryScore: 'স্মৃতি সূচক',
    attentionScore: 'মনোযোগ আৰু একাগ্রতা',
    recallScore: 'মনত পেলোৱাৰ গতি',
    reactionScore: 'প্ৰতিক্ৰিয়া সময়',
    overallScore: 'মুঠ ফল',
    dailyQuests: 'দৈনিক কাৰ্যসূচী',
    claimReward: 'পুৰস্কাৰ গ্ৰহণ কৰক',
    completed: 'সম্পূৰ্ণ',
    inProgress: 'চলমান',
    relicsShop: 'পুৰস্কাৰ ভঁৰাল',
    leaderboardTitle: 'গোলকীয় লিডাৰবৰ্ড',
    recentActivity: 'সম্প্ৰদায়ৰ জাননী',
    quickStart: 'প্ৰস্তাৱিত অনুশীলন',
    streakCount: 'দিনৰ ষ্ট্ৰীক',
    checkinToday: 'ষ্ট্ৰীক বজাই ৰাখিবলৈ অনুশীলন কৰক',
    alreadyChecked: 'আজিৰ অনুশীলন সম্পূৰ্ণ হ’ল 🔥',
    welcomeBack: 'পুনৰ স্বাগতম',
    signInSub: 'আপোনাৰ নিবন্ধিত ইমেইল আৰু পাছৱৰ্ডেৰে ছাইন ইন কৰক',
    emailLabel: 'ইমেইল ঠিকানা',
    passwordLabel: 'পাছৱৰ্ড',
    signInBtn: 'ছাইন ইন কৰক',
    authenticating: 'প্ৰমাণীকৰণ হৈ আছে...',
    noAccountText: 'একাউণ্ট নাইনে?',
    registerNowLink: 'এতিয়াই পঞ্জীয়ন কৰক',
    createAccount: 'একাউণ্ট সৃষ্টি কৰক',
    registerSub: 'মেমোমেট ডাটাবেছত আপোনাৰ প্ৰফাইল পঞ্জীয়ন কৰক',
    fullNameLabel: 'সম্পূৰ্ণ নাম',
    ageLabel: 'বয়স',
    accountRoleLabel: 'একাউণ্টৰ ভূমিকা',
    preferredLangLabel: 'পছন্দৰ ভাষা',
    confirmPasswordLabel: 'পাছৱৰ্ড নিশ্চিত কৰক',
    creatingAccount: 'একাউণ্ট সৃষ্টি কৰা হৈ আছে...',
    registerAccountBtn: 'একাউণ্ট পঞ্জীয়ন কৰক',
    alreadyRegisteredText: 'ইতিমধ্যে নিবন্ধিতনে?',
    logInHereLink: 'ইয়াত লগ ইন কৰক',
    logInWithThisAccount: 'এই একাউণ্টৰে লগ ইন কৰক →',
    enterEmailPassword: 'অনুগ্রহ কৰি আপোনাৰ ইমেইল ঠিকানা আৰু পাছৱৰ্ড দিয়ক',
    invalidEmailPassword: 'অবৈধ ইমেইল বা পাছৱৰ্ড।',
    valNameReq: 'সম্পূৰ্ণ নাম প্ৰয়োজন',
    valEmailReq: 'ইমেইল ঠিকানা প্ৰয়োজন',
    valEmailInvalid: 'অনুগ্রহ কৰি এখন বৈধ ইমেইল ঠিকানা দিয়ক',
    valPassReq: 'পাছৱৰ্ড প্ৰয়োজন',
    valPassMin: 'পাছৱৰ্ড কমেও ৬ টা আখৰৰ হ’ব লাগে',
    valPassMismatch: 'পাছৱৰ্ড মিল খোৱা নাই',
    regFailed: 'পঞ্জীয়ন বিফল হ’ল। ইমেইল ইতিমধ্যে নিবন্ধিত হ’ব পাৰে।',
    caregiverRole: 'যত্নলোৱা',
    voiceTitle: 'মেমোমেটৰ সৈতে কথা কওঁক',
    voiceSub: 'ভয়েচ এআই সহায়ক',
    voiceTapToSpeak: 'কথা ক’বলৈ টিপক',
    voiceListening: 'শুনি আছোঁ...',
    voiceProcessing: 'আপোনাৰ প্ৰশ্ন বুজি পাইছোঁ...',
    voiceSpeaking: 'উত্তৰ দি আছোঁ...',
    voiceError: 'স্পষ্টকৈ শুনি নাপালোঁ। অনুগ্রহ কৰি পুনৰ চেষ্টা কৰক।',
    voiceNoSupport: 'এই ব্ৰাউজাৰত কণ্ঠ চিনাক্তকৰণ সমর্থিত নহয়।',
    voiceNoLanguageVoice: 'এই সঁজুলিত অসমীয়া মাত উপলব্ধ নহয়। পাঠ্য দেখুওৱা হৈছে।',
    voicePromptInitial: 'নমস্কাৰ! আজি মই আপোনাক কেনেকৈ সহায় কৰিব পাৰোঁ?',
    voiceResponseTodayActivity: 'আজি আপুনি আপোনাৰ জ্ঞানভিত্তিক স্মৃতি অনুশীলন সম্পূৰ্ণ কৰিব লাগে। এতিয়াই আৰম্ভ কৰোঁনে?',
    voiceResponseHowAreYou: 'মই ভালে আছোঁ! আজি আপোনাৰ স্মৃতিশক্তি অনুশীলনত সহায় কৰিবলৈ সাজু।',
    voiceResponseGames: 'আমাৰ ওচৰত মেম’ৰী মেচ, ফকাছ ৰিফ্লেক্স, নম্বৰ ৰিকল, পেটাৰ্ন ৰিকল আৰু ৩ডি টাৰ্গেট চাৰ্চ আছে। আপুনি কোনটো খেলিব বিচাৰে?',
    voiceResponseFallback: 'আপোনাৰ মানসিক স্বাস্থ্যৰ সমৰ্থনৰ বাবে মই প্রতিদিনে ইয়াতেই আছোঁ। আপুনি আজিৰ কাৰ্যসূচী, খেল বা ঔষধৰ সোঁৱৰণী বিষয়ে সুধিব পাৰে।',
    voiceBtnYesStart: 'হয়, এতিয়াই আৰম্ভ কৰক',
    voiceBtnLater: 'পাছত',
    pts: 'পইণ্ট',
    startMissionNow: 'মিছন এতিয়াই আৰম্ভ কৰক',
    excellentRecall: 'চমৎকার স্মৃতিশক্তি!',
    missionComplete: 'মিছন সম্পূৰ্ণ হ’ল!',
    playAgain: 'পুনৰ খেলক',
    scoreMessage: 'স্কোৰ: {score} / ১০০ পইণ্ট',
    completedInMoves: '{moves} টা চালত সম্পূৰ্ণ হ’ল',
    roundInfo: 'ৰাউণ্ড {round} / {total}',
    scoreText: 'স্কোৰ: {score}',
    correctFeedback: 'শুদ্ধ! +{points} পইণ্ট ({time}ms)',
    wrongFeedback: 'ভুল! শুদ্ধ উত্তৰ: {answer}',
    matched: 'মিল হোৱা',
    moves: 'চাল',
    findSymbolPrompt: 'চিহ্ন বিচাৰক: {symbol}'
  },
  mni: {
    platformTitle: 'মেমোমেট — জ্ঞানাশ্রম গেমীং প্লেটফৰ্ম',
    dementiaSubtitle: 'নিংশিং থৌনা সহায়ক প্লেটফৰ্ম',
    goodMorning: 'আয়ুক অমুক',
    goodAfternoon: 'নুংথিল অমুক',
    goodEvening: 'নুমিদাং অমুক',
    goodNight: 'অহিং অমুক',
    activeMember: 'মেম্বর',
    dailyGoal: 'নুমিৎসিগী পান্দম',
    orientationHeader: 'নুমিৎসিগী নিংশিং সহায়ক 📍',
    orientationSub: 'মফম নিংশিং থৌনা',
    todaysDate: 'ঙসিগী তারিখ অমসুং মাতম',
    currentSeason: 'হৌজিক ঋতু',
    medicationCheck: 'আয়ুকগী হিদাং',
    medicationTaken: 'চাখ্রে ✓',
    medicationPending: 'নিংশিংহনবা 🔔',
    memoryAnchorPrompt: 'ইশাগী নিংশিং সহায়ক',
    memoryAnchorText: 'অদোম ইমুংগা লোয়ননা লাইবাক ফব নুমিৎনি।',
    startExercise: 'হৌদোকউ',
    navDashboard: 'ড্যাশবোর্ড',
    navLeaderboard: 'লিডারবোর্ড',
    navExercises: 'অনুশীলন',
    navTelemetry: 'এআই হেল্থ',
    navPath: 'লম্বী',
    navMetrics: 'মেট্রিক',
    navGarden: 'মাইন্ড মেট্রিক্স',
    navCaregiver: 'কেয়ারগিভার',
    streak: 'স্ট্রীক',
    level: 'লেভেল',
    rank: 'র‍্যাঙ্ক',
    audioOn: 'অডিও অন',
    audioOff: 'অডিও অফ',
    patientView: 'রোগীর ভিউ',
    caregiverView: 'কেয়ারগিভার ভিউ',
    logout: 'লগআউট',
    readAnchorAloud: 'পাবিয়ু',
    water3dGarden: 'চাজ তৌবা ⚡',
    vrMode: 'ভিআৰ মোড 👓',
    memoryScore: 'নিংশিং স্কোর',
    attentionScore: 'মিৎয়েং',
    recallScore: 'নিংশিংবা য়াংবা',
    reactionScore: 'পাউখুম মাতম',
    overallScore: 'অপুনবা স্কোর',
    dailyQuests: 'নুমিৎসিগী থৌরম',
    claimReward: 'মনা লৌবা',
    completed: 'লোইখ্রে',
    inProgress: 'চত্থরি',
    relicsShop: 'মনা দোকান',
    leaderboardTitle: 'লিডারবোর্ড',
    recentActivity: 'লাইভ ফীদ',
    quickStart: 'হৌদোকফম',
    streakCount: 'নুমিৎ স্ট্রীক',
    checkinToday: 'স্ট্রীক থম্বাগীদমক থৌরম লোইশিনবিয়ু',
    alreadyChecked: 'ঙসিগী অনুশীলন লোইখ্রে 🔥'
  },
  kha: {
    platformTitle: 'MemoMate — Cognitive Gaming Platform',
    dementiaSubtitle: 'AI Cognitive Assistance & Memory Support Platform',
    goodMorning: 'Khyndai Mynstep',
    goodAfternoon: 'Khein Mynsngi',
    goodEvening: 'Khein Mynstep',
    goodNight: 'Mynmiet Bha',
    activeMember: 'ACTIVE MEMBER',
    dailyGoal: 'DAILY GOAL',
    orientationHeader: 'Daily Memory Anchor 📍',
    orientationSub: 'Location & Memory Assistance',
    todaysDate: "Today's Date & Time",
    currentSeason: 'Current Season',
    medicationCheck: 'Morning Medicine',
    medicationTaken: 'Taken ✓',
    medicationPending: 'Reminder 🔔',
    memoryAnchorPrompt: 'Personal Memory Anchor',
    memoryAnchorText: 'You are at home in a peaceful environment with family.',
    startExercise: 'START EXERCISE NOW',
    navDashboard: 'Dashboard',
    navLeaderboard: 'Leaderboard',
    navExercises: 'Cognitive Exercises',
    navTelemetry: 'AI Health Telemetry',
    navPath: 'Cognitive Path',
    navMetrics: 'Metrics & Trends',
    navGarden: 'Mind Matrix Sanctum',
    navCaregiver: 'Caregiver Portal',
    streak: 'Streak',
    level: 'Level',
    rank: 'Rank',
    audioOn: 'AUDIO ON',
    audioOff: 'AUDIO OFF',
    patientView: 'Patient View',
    caregiverView: 'Caregiver View',
    logout: 'Logout',
    readAnchorAloud: 'READ ALOUD',
    water3dGarden: 'CHARGING NEURAL MATRIX ⚡',
    vrMode: 'TOGGLE VR MODE 👓',
    memoryScore: 'Memory Index',
    attentionScore: 'Focus & Attention',
    recallScore: 'Recall Speed',
    reactionScore: 'Reaction Time',
    overallScore: 'Overall Performance',
    dailyQuests: 'Daily Cognitive Quests',
    claimReward: 'Claim Reward',
    completed: 'Completed',
    inProgress: 'In Progress',
    relicsShop: 'Cognitive Relics & Rewards Store',
    leaderboardTitle: 'Global Leaderboard',
    recentActivity: 'Live Community Feed',
    quickStart: 'Recommended Training Mission',
    streakCount: 'Day Streak',
    checkinToday: 'Complete Exercise to Maintain Streak',
    alreadyChecked: 'Daily Exercise Completed 🔥'
  }
};
